Title: arrayWeights(method="reml") with prior weights stops after one or two iterations: convergence criterion divided by (ngenes+prior.n) twice

<!-- Bioconductor support site post (https://support.bioconductor.org, tag: limma). limma has no
     issue tracker; this is the channel named in vignettes/intro.Rmd. Attach the patch from this
     directory (0001-...RELEASE_3_23.patch for the release branch, 0001-...-pr.patch for devel). -->

`arrayWeights()` has two REML routines: `.arrayWeightsREML()` when there are no prior weights
and `.arrayWeightsPrWtsREML()` when there are (`method="reml"` on a voom EList, or
`voomWithQualityWeights(method="reml")`). They run the same Fisher-scoring update, but the
second one divides its convergence criterion by `ngenes+prior.n` a second time —
`z` and `info2` are already averaged per gene at that point — so for the same state its
`convcrit` is exactly `ngenes+prior.n` times smaller than the first routine's, and the
default `tol=1e-5` is met after one or two iterations. With a weight matrix of ones the two
routines fit the same model but return different weights.

**Minimal example** (limma 3.68.5, R 4.3.3; identical on 3.42.2, 3.58.1, 3.62.2, 3.68.4 and
devel 3.99.0, whose C backend `src/awreml.c` reproduces the R code):

```r
library(limma)
set.seed(1)
G <- 10000; n <- 8
design <- cbind(1, rep(0:1, each=4))
y <- matrix(rnorm(G*n, sd=rep(c(0.5, 0.7, 1, 1.4, 0.5, 0.7, 1, 1.4), each=G)), G, n)
w0 <- arrayWeights(y, design, method="reml")                         # .arrayWeightsREML
w1 <- arrayWeights(y, design, weights=matrix(1, G, n), method="reml")# .arrayWeightsPrWtsREML
round(rbind(w0, w1), 4)
#>         1      2      3      4      5      6      7      8
#> w0 2.8478 1.4554 0.6867 0.3566 2.7678 1.4140 0.7174 0.3510
#> w1 2.4377 1.4828 0.7358 0.3786 2.3963 1.4468 0.7669 0.3735
arrayWeights(y, design, method="reml", trace=TRUE)
#> iter convcrit range(w)
#> 1 0.1744177 0.4238892 1.826388
#> 2 0.01525544 0.3735225 2.43771
#> 3 0.001427447 0.3568687 2.72955
#> 4 0.0001032856 0.3521681 2.823373
#> 5 6.315427e-06 0.3509565 2.847802
arrayWeights(y, design, weights=matrix(1, G, n), method="reml", trace=TRUE)
#> iter convcrit range(w)
#> 1 1.742434e-05 0.4238892 1.826388                # the same state, criterion 10010 times smaller
#> 2 1.52402e-06 0.3735225 2.43771                  # stops
```

**Expected:** `w1 == w0` (same model, same algorithm, same tolerance). **Got:** weights up
to 14.4 % apart (2.4377 vs 2.8478; the true relative precisions are 2.83, 1.41, 0.71, 0.35);
the prior-weights routine stops after 2 iterations where the other needs 5, and its
iteration-1 `convcrit` is 0.1744177/1.742434e-05 = 10010.0 = `ngenes+prior.n` times smaller
(the `range(w)` columns are identical, so the states are the same). Passing
`tol=1e-5/(G+10)` to the prior-weights call reproduces `w0` to 8.4e-14, which locates the
missing factor.

**Effect downstream:** on 8,000 simulated genes with two poor-quality samples,
`voomWithQualityWeights(counts, design, method="reml")` returns sample weights 0.0991 2.2100
2.1469 2.0679 0.1004 2.1569 2.1343 2.2235 at the default tolerance against 0.0888 2.3114
2.2198 2.1118 0.0906 2.2398 2.2131 2.3159 when converged (up to 11.7 % apart), and the
downstream `eBayes` calls 137 genes at adj.P < 0.05 instead of 183 (of 800 true). On the
devel branch the new `voomLmFit(sample.weights=TRUE)` calls `arrayWeights(method="reml")`
with the voom weights whenever no df are lost to exact zeros, so this path becomes the
default sample-weight estimator in 4.0.0.

Shrinking the example showed what it needs: nothing but prior weights and `method="reml"`;
the design, the number of arrays and the true weights only change the size of the gap, which
grows with the number of iterations the converged fit would take.

**Where** (3.68.5 `R/arrayWeightsPrWtsREML.R`, lines 65-66 and 77; devel `src/awreml.c`
lines 357-359 and 403):

```r
info2 <- info2 / (ngenes+prior.n)
z <- z / (ngenes+prior.n)
...
convcrit <- crossprod(dl,gamstep) / (ngenes+prior.n) / ngam
```

whereas `.arrayWeightsREML()` (`R/arrayWeightsREML.R:81-82, 89`) divides the *total* score
and information by `ngenes+prior.n` once, in the criterion.

**Proposed fix** (patches attached, one per branch): `convcrit <- crossprod(dl,gamstep) / ngam`
in R, `convcrit = num / ngam;` in `awreml.c`. With it the two routines agree to rounding on
equal prior weights (5 iterations each) and `tests/arrayweights-reml.R` (added) passes;
without it the test fails on both branches. `tests/limma-Tests.R` gives the same `R CMD
Rdiff` output with and without the patch, and the five devel C test files pass.

Found in Mytochondria, a volunteer project that checks the numerical core of research software and verifies every finding by execution (methods and harnesses: https://github.com/cindykrafft/mytochondria/tree/main/audits/limma)

---
_Generated by [Claude Code](https://claude.ai/code)_

**Session info**

```
R version 4.3.3 (2024-02-29), x86_64-pc-linux-gnu
limma 3.68.5 (RELEASE_3_23 @ 825d1c83, built from source), statmod 1.5.0
also run on limma 3.42.2, 3.58.1, 3.62.2, 3.68.4 and devel 3.99.0 (57a8de72)
```
