#!/usr/bin/env python3
"""Dictionary of open-source scientific software packages.

Two tiers:
  SAFE      - name is unambiguous; plain word-boundary match is enough.
  AMBIGUOUS - name collides with ordinary English or domain vocabulary
              ("STAR" vs Cell's "STAR Methods", MUSCLE vs muscle tissue,
              Salmon vs the fish, Fiji vs the country). These require a
              disambiguating context pattern to count as a hit.
Each entry: canonical name -> (category, [aliases])
"""

SAFE = {
 # ---- neuroimaging ----
 "AFNI": ("neuroimaging", ["AFNI"]),
 "SUMA": ("neuroimaging", ["SUMA"]),
 "FSL": ("neuroimaging", ["FSL", "FMRIB Software Library"]),
 "FreeSurfer": ("neuroimaging", ["FreeSurfer", "Freesurfer"]),
 "SPM": ("neuroimaging", ["SPM12", "SPM8", "Statistical Parametric Mapping"]),
 "ANTs": ("neuroimaging", ["ANTs", "Advanced Normalization Tools", "ANTsPy"]),
 "fMRIPrep": ("neuroimaging", ["fMRIPrep", "fMRIprep", "FMRIPREP"]),
 "MRIQC": ("neuroimaging", ["MRIQC"]),
 "QSIPrep": ("neuroimaging", ["QSIPrep", "qsiprep"]),
 "Nipype": ("neuroimaging", ["Nipype", "nipype"]),
 "Nilearn": ("neuroimaging", ["Nilearn", "nilearn"]),
 "NiBabel": ("neuroimaging", ["NiBabel", "nibabel"]),
 "MRtrix3": ("neuroimaging", ["MRtrix3", "MRtrix"]),
 "DIPY": ("neuroimaging", ["DIPY", "Dipy"]),
 "Connectome Workbench": ("neuroimaging", ["Connectome Workbench", "wb_command"]),
 "CONN toolbox": ("neuroimaging", ["CONN toolbox", "CONN functional connectivity"]),
 "dcm2niix": ("neuroimaging", ["dcm2niix", "dcm2nii"]),
 "HeuDiConv": ("neuroimaging", ["HeuDiConv", "heudiconv"]),
 "TractoFlow": ("neuroimaging", ["TractoFlow"]),
 "Camino": ("neuroimaging", ["Camino"]),
 "BrainSuite": ("neuroimaging", ["BrainSuite"]),
 "CIVET": ("neuroimaging", ["CIVET"]),
 "EEGLAB": ("neuroimaging", ["EEGLAB"]),
 "MNE-Python": ("neuroimaging", ["MNE-Python", "MNE Python", "mne-python"]),
 "FieldTrip": ("neuroimaging", ["FieldTrip", "Fieldtrip"]),
 "Brainstorm": ("neuroimaging", ["Brainstorm toolbox"]),
 "BrainNet Viewer": ("neuroimaging", ["BrainNet Viewer"]),
 "PALM": ("neuroimaging", ["PALM (Permutation Analysis"]),
 # ---- sequence alignment / NGS ----
 "BWA": ("genomics", ["BWA-MEM", "BWA mem", "bwa-mem", "BWA aligner", "BWA "]),
 "Bowtie2": ("genomics", ["Bowtie2", "Bowtie 2", "bowtie2"]),
 "HISAT2": ("genomics", ["HISAT2", "HISAT 2", "hisat2"]),
 "TopHat": ("genomics", ["TopHat2", "TopHat"]),
 "minimap2": ("genomics", ["minimap2", "Minimap2"]),
 "SAMtools": ("genomics", ["SAMtools", "Samtools", "samtools"]),
 "BCFtools": ("genomics", ["BCFtools", "bcftools"]),
 "BEDTools": ("genomics", ["BEDTools", "bedtools", "BEDtools"]),
 "Picard": ("genomics", ["Picard"]),
 "GATK": ("genomics", ["GATK", "Genome Analysis Toolkit"]),
 "VCFtools": ("genomics", ["VCFtools", "vcftools"]),
 "Trimmomatic": ("genomics", ["Trimmomatic"]),
 "Cutadapt": ("genomics", ["Cutadapt", "cutadapt"]),
 "fastp": ("genomics", ["fastp"]),
 "Trim Galore": ("genomics", ["Trim Galore", "TrimGalore"]),
 "FastQC": ("genomics", ["FastQC"]),
 "MultiQC": ("genomics", ["MultiQC"]),
 "kallisto": ("genomics", ["kallisto", "Kallisto"]),
 "RSEM": ("genomics", ["RSEM"]),
 "featureCounts": ("genomics", ["featureCounts", "FeatureCounts"]),
 "HTSeq": ("genomics", ["HTSeq", "htseq-count"]),
 "StringTie": ("genomics", ["StringTie"]),
 "Cufflinks": ("genomics", ["Cufflinks"]),
 "Trinity": ("genomics", ["Trinity assembler", "Trinity (v", "Trinity RNA-seq"]),
 "SPAdes": ("genomics", ["SPAdes"]),
 "Flye": ("genomics", ["Flye"]),
 "Canu": ("genomics", ["Canu"]),
 "MACS2": ("genomics", ["MACS2", "MACS3", "MACS "]),
 "HOMER": ("genomics", ["HOMER"]),
 "deepTools": ("genomics", ["deepTools", "deeptools"]),
 "Bismark": ("genomics", ["Bismark"]),
 "Salmon": ("genomics", ["Salmon (v", "salmon (v", "Salmon v", "salmon quantification"]),
 # ---- differential expression / single cell ----
 "DESeq2": ("genomics", ["DESeq2", "DESeq 2"]),
 "edgeR": ("genomics", ["edgeR", "EdgeR"]),
 "limma": ("genomics", ["limma"]),
 "Seurat": ("single-cell", ["Seurat"]),
 "Scanpy": ("single-cell", ["Scanpy", "scanpy"]),
 "AnnData": ("single-cell", ["AnnData", "anndata"]),
 "Monocle": ("single-cell", ["Monocle3", "Monocle 3", "Monocle2", "Monocle"]),
 "scVelo": ("single-cell", ["scVelo", "scvelo"]),
 "velocyto": ("single-cell", ["velocyto", "Velocyto"]),
 "Harmony": ("single-cell", ["Harmony (v", "Harmony integration", "harmony R package"]),
 "CellPhoneDB": ("single-cell", ["CellPhoneDB"]),
 "CellChat": ("single-cell", ["CellChat"]),
 "SCENIC": ("single-cell", ["SCENIC", "pySCENIC"]),
 "Slingshot": ("single-cell", ["Slingshot"]),
 "UMAP": ("single-cell", ["UMAP"]),
 "scDblFinder": ("single-cell", ["scDblFinder", "DoubletFinder", "Scrublet"]),
 "SoupX": ("single-cell", ["SoupX"]),
 "Signac": ("single-cell", ["Signac"]),
 "ArchR": ("single-cell", ["ArchR"]),
 "Squidpy": ("single-cell", ["Squidpy", "squidpy"]),
 # ---- phylogenetics / microbiome ----
 "RAxML": ("phylogenetics", ["RAxML", "RAxML-NG"]),
 "IQ-TREE": ("phylogenetics", ["IQ-TREE", "IQTREE"]),
 "MrBayes": ("phylogenetics", ["MrBayes"]),
 "BEAST": ("phylogenetics", ["BEAST2", "BEAST 2", "BEAST v", "BEAST (v"]),
 "MAFFT": ("phylogenetics", ["MAFFT"]),
 "Clustal Omega": ("phylogenetics", ["Clustal Omega", "ClustalW", "Clustal W"]),
 "HMMER": ("phylogenetics", ["HMMER", "hmmscan", "hmmsearch"]),
 "BLAST": ("phylogenetics", ["BLASTn", "BLASTp", "BLASTx", "NCBI BLAST", "blastn", "blastp"]),
 "DIAMOND": ("phylogenetics", ["DIAMOND (v", "DIAMOND blastx", "DIAMOND aligner"]),
 "TreeTime": ("phylogenetics", ["TreeTime"]),
 "Nextstrain": ("phylogenetics", ["Nextstrain", "Nextclade", "Augur"]),
 "Pangolin": ("phylogenetics", ["Pangolin", "pangolin lineage"]),
 "QIIME 2": ("microbiome", ["QIIME 2", "QIIME2", "QIIME"]),
 "DADA2": ("microbiome", ["DADA2"]),
 "mothur": ("microbiome", ["mothur"]),
 "Kraken2": ("microbiome", ["Kraken2", "Kraken 2"]),
 "Bracken": ("microbiome", ["Bracken"]),
 "MetaPhlAn": ("microbiome", ["MetaPhlAn", "MetaPhlan"]),
 "HUMAnN": ("microbiome", ["HUMAnN"]),
 "Prokka": ("microbiome", ["Prokka"]),
 "phyloseq": ("microbiome", ["phyloseq"]),
 # ---- statistical genetics ----
 "PLINK": ("statgen", ["PLINK", "plink2", "PLINK2"]),
 "GCTA": ("statgen", ["GCTA"]),
 "LDSC": ("statgen", ["LDSC", "LD Score Regression", "LD score regression"]),
 "METAL": ("statgen", ["METAL software", "METAL (v"]),
 "MAGMA": ("statgen", ["MAGMA"]),
 "FUMA": ("statgen", ["FUMA"]),
 "Beagle": ("statgen", ["Beagle (v", "BEAGLE v", "Beagle v"]),
 "SHAPEIT": ("statgen", ["SHAPEIT"]),
 "IMPUTE2": ("statgen", ["IMPUTE2", "IMPUTE4", "Minimac"]),
 "ADMIXTURE": ("statgen", ["ADMIXTURE"]),
 "ANGSD": ("statgen", ["ANGSD"]),
 "GEMMA": ("statgen", ["GEMMA"]),
 "SAIGE": ("statgen", ["SAIGE"]),
 "REGENIE": ("statgen", ["REGENIE", "regenie"]),
 "Hail": ("statgen", ["Hail (v", "Hail 0."]),
 "TwoSampleMR": ("statgen", ["TwoSampleMR", "MR-Base", "MendelianRandomization package"]),
 "COLOC": ("statgen", ["coloc R package", "COLOC (v"]),
 # ---- structural biology / cryo-EM ----
 "PyMOL": ("structbio", ["PyMOL", "PyMol"]),
 "ChimeraX": ("structbio", ["ChimeraX", "Chimera X"]),
 "UCSF Chimera": ("structbio", ["UCSF Chimera"]),
 "Coot": ("structbio", ["Coot (v", "Coot v", "COOT (v", "in Coot"]),
 "PHENIX": ("structbio", ["PHENIX", "Phenix"]),
 "RELION": ("structbio", ["RELION", "Relion"]),
 "CTFFIND": ("structbio", ["CTFFIND", "Gctf"]),
 "MotionCor2": ("structbio", ["MotionCor2", "MotionCorr"]),
 "EMAN2": ("structbio", ["EMAN2"]),
 "Topaz": ("structbio", ["Topaz"]),
 "AlphaFold": ("structbio", ["AlphaFold2", "AlphaFold 2", "AlphaFold3", "AlphaFold"]),
 "ColabFold": ("structbio", ["ColabFold"]),
 "RoseTTAFold": ("structbio", ["RoseTTAFold", "RosettaFold"]),
 "Rosetta": ("structbio", ["Rosetta suite", "PyRosetta", "Rosetta (v"]),
 "XDS": ("structbio", ["XDS package", "XDS (v"]),
 "CCP4": ("structbio", ["CCP4"]),
 "REFMAC": ("structbio", ["REFMAC"]),
 "IMOD": ("structbio", ["IMOD"]),
 "cryoDRGN": ("structbio", ["cryoDRGN"]),
 # ---- molecular dynamics / chemistry ----
 "GROMACS": ("md", ["GROMACS", "Gromacs"]),
 "NAMD": ("md", ["NAMD"]),
 "AMBER": ("md", ["AMBER (v", "AMBER1", "AMBER2", "Amber force field", "AmberTools"]),
 "OpenMM": ("md", ["OpenMM"]),
 "CHARMM": ("md", ["CHARMM"]),
 "LAMMPS": ("md", ["LAMMPS"]),
 "VMD": ("md", ["VMD"]),
 "MDAnalysis": ("md", ["MDAnalysis"]),
 "MDTraj": ("md", ["MDTraj", "mdtraj"]),
 "PLUMED": ("md", ["PLUMED"]),
 "AutoDock Vina": ("md", ["AutoDock Vina", "AutoDock"]),
 "RDKit": ("md", ["RDKit", "rdkit"]),
 "Open Babel": ("md", ["Open Babel", "OpenBabel"]),
 "Quantum ESPRESSO": ("md", ["Quantum ESPRESSO", "Quantum Espresso"]),
 "VASP": ("md", ["VASP"]),
 "PySCF": ("md", ["PySCF"]),
 "ASE": ("md", ["Atomic Simulation Environment"]),
 # ---- imaging / microscopy ----
 "ImageJ": ("imaging", ["ImageJ"]),
 "Fiji": ("imaging", ["Fiji (ImageJ", "Fiji/ImageJ", "Fiji, ImageJ", "Fiji ImageJ"]),
 "CellProfiler": ("imaging", ["CellProfiler"]),
 "napari": ("imaging", ["napari"]),
 "QuPath": ("imaging", ["QuPath"]),
 "ilastik": ("imaging", ["ilastik", "Ilastik"]),
 "TrackMate": ("imaging", ["TrackMate"]),
 "Cellpose": ("imaging", ["Cellpose", "CellPose"]),
 "StarDist": ("imaging", ["StarDist"]),
 "scikit-image": ("imaging", ["scikit-image", "skimage"]),
 "OpenCV": ("imaging", ["OpenCV"]),
 "Imaris": ("imaging", ["Imaris"]),
 "BigStitcher": ("imaging", ["BigStitcher", "BigDataViewer"]),
 # ---- neuroscience / behavior ----
 "DeepLabCut": ("neuro-tools", ["DeepLabCut"]),
 "SLEAP": ("neuro-tools", ["SLEAP"]),
 "Suite2p": ("neuro-tools", ["Suite2p", "suite2p"]),
 "CaImAn": ("neuro-tools", ["CaImAn"]),
 "Kilosort": ("neuro-tools", ["Kilosort", "KiloSort"]),
 "SpikeInterface": ("neuro-tools", ["SpikeInterface"]),
 "Phy": ("neuro-tools", ["phy (v", "Phy GUI", "phy GUI"]),
 "NEURON": ("neuro-tools", ["NEURON simulat", "NEURON (v"]),
 "NEST": ("neuro-tools", ["NEST simulator"]),
 "Brian2": ("neuro-tools", ["Brian2", "Brian 2"]),
 "PsychoPy": ("neuro-tools", ["PsychoPy"]),
 "Psychtoolbox": ("neuro-tools", ["Psychtoolbox"]),
 # ---- workflow / infra ----
 "Nextflow": ("workflow", ["Nextflow"]),
 "Snakemake": ("workflow", ["Snakemake", "snakemake"]),
 "Galaxy": ("workflow", ["Galaxy platform", "Galaxy server"]),
 "Docker": ("workflow", ["Docker"]),
 "Singularity": ("workflow", ["Singularity", "Apptainer"]),
 "Conda": ("workflow", ["Conda", "Bioconda", "Miniconda", "Anaconda"]),
 "Jupyter": ("workflow", ["Jupyter", "IPython"]),
 "Dask": ("workflow", ["Dask", "dask"]),
 "Snakemake": ("workflow", ["Snakemake"]),
 # ---- general stats / ML ----
 "NumPy": ("general", ["NumPy", "Numpy", "numpy"]),
 "SciPy": ("general", ["SciPy", "Scipy", "scipy"]),
 "pandas": ("general", ["pandas library", "pandas (v", "Pandas (v", "pandas Python"]),
 "scikit-learn": ("general", ["scikit-learn", "sklearn", "Scikit-learn"]),
 "statsmodels": ("general", ["statsmodels"]),
 "Matplotlib": ("general", ["Matplotlib", "matplotlib"]),
 "seaborn": ("general", ["seaborn", "Seaborn"]),
 "TensorFlow": ("general", ["TensorFlow", "Tensorflow"]),
 "PyTorch": ("general", ["PyTorch", "Pytorch", "pytorch"]),
 "Keras": ("general", ["Keras"]),
 "JAX": ("general", ["JAX (v", "JAX library", "Google JAX"]),
 "XGBoost": ("general", ["XGBoost", "xgboost"]),
 "LightGBM": ("general", ["LightGBM"]),
 "Stan": ("general", ["RStan", "CmdStan", "PyStan", "Stan (v", "Stan probabilistic"]),
 "PyMC": ("general", ["PyMC3", "PyMC"]),
 "JAGS": ("general", ["JAGS"]),
 "brms": ("general", ["brms"]),
 "lme4": ("general", ["lme4", "lmerTest"]),
 "ggplot2": ("general", ["ggplot2"]),
 "tidyverse": ("general", ["tidyverse", "dplyr", "tidyr"]),
 "Bioconductor": ("general", ["Bioconductor"]),
 "survival (R)": ("general", ["survival R package", "survminer"]),
 "metafor": ("general", ["metafor"]),
 "NetworkX": ("general", ["NetworkX", "networkx"]),
 "igraph": ("general", ["igraph"]),
 "xarray": ("general", ["xarray"]),
 # ---- astro / physics / earth ----
 "Astropy": ("physical", ["Astropy", "astropy"]),
 "emcee": ("physical", ["emcee"]),
 "healpy": ("physical", ["healpy", "HEALPix"]),
 "CASA": ("physical", ["CASA (Common Astronomy", "CASA software"]),
 "ROOT": ("physical", ["ROOT (CERN", "CERN ROOT", "ROOT framework"]),
 "Geant4": ("physical", ["Geant4", "GEANT4"]),
 "OpenFOAM": ("physical", ["OpenFOAM"]),
 "Cantera": ("physical", ["Cantera"]),
 "WRF": ("physical", ["WRF model", "Weather Research and Forecasting"]),
 "CESM": ("physical", ["CESM", "Community Earth System Model"]),
 "GDAL": ("physical", ["GDAL"]),
 "QGIS": ("physical", ["QGIS"]),
}

# Names requiring a disambiguating context match.
AMBIGUOUS = {
 "STAR": ("genomics",
          r"STAR\s*\(?v|STAR\s+aligner|STAR\s+2\.|aligned\s+(?:to|with|using)[^.]{0,40}\bSTAR\b|"
          r"\bSTAR\b[^.]{0,30}(?:aligner|alignment|genome index)",
          r"STAR\s*[★☆]?\s*Methods"),
 "R": ("general",
       r"\bR\s+\(version|\bR\s+v?\d+\.\d+|R\s+Core\s+Team|R\s+statistical\s+(?:software|computing|environment)|"
       r"\bin\s+R\s+\(|R\s+Foundation\s+for\s+Statistical",
       None),
 "MATLAB": ("general", r"MATLAB", None),
 "MUSCLE": ("phylogenetics", r"MUSCLE\s*\(?v|MUSCLE\s+align|aligned[^.]{0,30}MUSCLE", None),
 "Python": ("general", r"Python\s+\d|Python\s+\(version|Python\s+script|in\s+Python", None),
}

# Signals used to discover packages not in the dictionary.
DISCOVERY = {
 "rrid":    r"RRID:\s*(SCR_\d+)",
 "github":  r"https?://(?:www\.)?github\.com/([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)",
 "zenodo":  r"(10\.5281/zenodo\.\d+)",
 "version": r"\b([A-Z][A-Za-z0-9_+.-]{2,24})\s+(?:v(?:er|ersion)?\.?\s*)(\d+\.\d[\w.]*)",
 "cran":    r"https?://cran\.r-project\.org/(?:web/)?packages?/([A-Za-z0-9._-]+)",
 "bioc":    r"bioconductor\.org/packages/(?:release/bioc/html/)?([A-Za-z0-9._-]+)",
}

# --- second pass additions -------------------------------------------------
EXTRA = {
 # stats / psych / R ecosystem
 "lavaan": ("general", ["lavaan"]),
 "afex": ("general", ["afex"]),
 "emmeans": ("general", ["emmeans"]),
 "rstanarm": ("general", ["rstanarm"]),
 "pingouin": ("general", ["pingouin"]),
 "jsPsych": ("neuro-tools", ["jsPsych", "jspsych"]),
 "JASP": ("general", ["JASP"]),
 "vegan": ("microbiome", ["vegan R package", "vegan (v", "vegan package"]),
 "ape (R)": ("phylogenetics", ["ape R package", "ape (v"]),
 "phytools": ("phylogenetics", ["phytools"]),
 "ComplexHeatmap": ("general", ["ComplexHeatmap"]),
 "pheatmap": ("general", ["pheatmap"]),
 "ggpubr": ("general", ["ggpubr"]),
 "Rcpp": ("general", ["Rcpp"]),
 "data.table": ("general", ["data.table"]),
 # enrichment / pathway
 "clusterProfiler": ("genomics", ["clusterProfiler"]),
 "GSEA": ("genomics", ["GSEA", "Gene Set Enrichment Analysis"]),
 "fgsea": ("genomics", ["fgsea"]),
 "GSVA": ("genomics", ["GSVA"]),
 "WGCNA": ("genomics", ["WGCNA"]),
 "Metascape": ("genomics", ["Metascape"]),
 "DAVID": ("genomics", ["DAVID (Database for Annotation", "DAVID bioinformatics"]),
 "Enrichr": ("genomics", ["Enrichr"]),
 "Cytoscape": ("genomics", ["Cytoscape"]),
 "STRING db": ("genomics", ["STRING database", "STRINGdb"]),
 # variant / annotation
 "SnpEff": ("genomics", ["SnpEff", "SnpSift"]),
 "ANNOVAR": ("genomics", ["ANNOVAR"]),
 "VEP": ("genomics", ["Variant Effect Predictor", "Ensembl VEP"]),
 "DeepVariant": ("genomics", ["DeepVariant"]),
 "freebayes": ("genomics", ["freebayes", "FreeBayes"]),
 "Strelka": ("genomics", ["Strelka"]),
 "Manta": ("genomics", ["Manta (v", "Manta structural"]),
 "DELLY": ("genomics", ["DELLY", "Delly"]),
 "CNVkit": ("genomics", ["CNVkit"]),
 "Mutect2": ("genomics", ["Mutect2", "MuTect"]),
 "VarScan": ("genomics", ["VarScan"]),
 "WhatsHap": ("genomics", ["WhatsHap"]),
 # assembly / annotation / long read
 "OrthoFinder": ("phylogenetics", ["OrthoFinder"]),
 "BUSCO": ("phylogenetics", ["BUSCO"]),
 "QUAST": ("genomics", ["QUAST"]),
 "Guppy": ("genomics", ["Guppy basecall", "Guppy (v"]),
 "Dorado": ("genomics", ["Dorado basecall"]),
 "Medaka": ("genomics", ["Medaka", "medaka"]),
 "NanoPlot": ("genomics", ["NanoPlot", "NanoComp"]),
 "hifiasm": ("genomics", ["hifiasm"]),
 "Pilon": ("genomics", ["Pilon"]),
 "RepeatMasker": ("genomics", ["RepeatMasker", "RepeatModeler"]),
 "AUGUSTUS": ("genomics", ["AUGUSTUS"]),
 "MEGA": ("phylogenetics", ["MEGA11", "MEGA X", "MEGA7"]),
 "InterProScan": ("phylogenetics", ["InterProScan"]),
 "eggNOG": ("phylogenetics", ["eggNOG"]),
 # physical sciences
 "yt": ("physical", ["yt-project", "yt analysis"]),
 "Cloudy": ("physical", ["Cloudy photoionization"]),
 "GADGET": ("physical", ["GADGET-2", "GADGET-4", "GADGET simulation"]),
 "AREPO": ("physical", ["AREPO"]),
 "SExtractor": ("physical", ["SExtractor", "Source Extractor"]),
 "lightkurve": ("physical", ["lightkurve"]),
 "PyMC3": ("general", ["PyMC3"]),
 "dynesty": ("physical", ["dynesty", "MultiNest", "PyMultiNest"]),
 "Cartopy": ("physical", ["Cartopy"]),
 "NCO": ("physical", ["NCO (netCDF", "netCDF Operators"]),
 "CDO": ("physical", ["Climate Data Operators"]),
 "MOM6": ("physical", ["MOM6", "MITgcm"]),
}
SAFE.update(EXTRA)

# Widen a few context patterns that under-matched in testing.
AMBIGUOUS["R"] = ("general",
    r"\bR\s+\(version|\bR\s+version\s+\d|\bR\s+v?\d+\.\d+|R\s+Core\s+Team|"
    r"R\s+statistical\s+(?:software|computing|environment|package)|\bin\s+R\s+\(|"
    r"R\s+Foundation\s+for\s+Statistical|\bR\s+package\b|\(R,\s*v",
    None)
AMBIGUOUS["Stan"] = ("general",
    r"RStan|CmdStan|PyStan|Stan\s*\(v|Stan\s+probabilistic|"
    r"\bStan\b(?=[^.]{0,60}(?:model|sampl|MCMC|Bayes|posterior))|"
    r"(?:using|in|with)\s+Stan\b",
    None)

# Tools that are NOT open source - tracked for context, reported separately.
PROPRIETARY = {
 "MATLAB", "Imaris", "VASP", "AMBER", "CHARMM", "Rosetta", "MEGA", "JASP",
 "DAVID", "Guppy", "Dorado", "XDS",
}
