import json, re, os, urllib.parse as u
ROOT=os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
A=ROOT+"/audits/"
OUT=os.path.join(os.path.dirname(os.path.abspath(__file__)), "out"); os.makedirs(OUT, exist_ok=True)
FOOTER="\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
def foot(b): return b if "Generated by [Claude Code]" in b else b.rstrip()+FOOTER
def strip_comment(s): return re.sub(r"<!--.*?-->\s*", "", s, count=1, flags=re.S).strip()
def read(p): return open(p, encoding="utf-8").read()
def title_body_titleline(s):
    m=re.search(r"^Title:\s*(.+)$", s, re.M); t=m.group(1).strip()
    body=s[m.end():]; return t, foot(strip_comment(body))
def cutadapt_issue(s):
    m=re.search(r"^\*\*Title:\*\*\s*(.+)$", s, re.M); t=m.group(1).strip()
    body=s[m.end():].strip(); return t, foot(body)
def scanpy_issue(s):
    t=re.search(r"^# Bug report:\s*(.+)$", s, re.M).group(1).strip()
    desc=re.search(r"\*\*What happened\?\*\*\s*(.*?)\*\*Minimal code sample\*\*", s, re.S).group(1).strip()
    code=re.search(r"\*\*Minimal code sample\*\*.*?```python\n(.*?)```", s, re.S).group(1)
    tb=re.search(r"\*\*Error output\*\*\s*(.*?)\*\*Versions\*\*", s, re.S).group(1).strip()
    tb=re.sub(r"^```\w*\n|\n```$", "", tb.strip()).strip()
    ver=s[s.index("**Versions**")+len("**Versions**"):].strip()
    return t, foot(desc), code, tb, ver
def pr_sections(s):
    out=[]
    for m in re.finditer(r"^## (PR \d+[^\n]*)\n(.*?)(?=^## |\Z)", s, re.S|re.M):
        sec=m.group(2); tm=re.search(r"^\*\*Title:\*\*\s*(.+)$", sec, re.M)
        if not tm: continue
        out.append((tm.group(1).strip(), foot(sec[tm.end():].strip())))
    return out
repos={}
# ---- stale bases: upstream rewrote its tree after the kit was made; nothing files until re-verified
STALE_OFF={"deeptools":"deepTools squash-merged its 4.0.0 rewrite into master on 2026-09-04 (4db9d816: Rust backend, Python moved to pydeeptools/). Every patch here was made against 3.5.6 and no longer applies; PyPI still ships 3.5.6. Re-verification against 4.0.0 is in progress; file nothing from this section until it lands."}
# ---- cutadapt
ci=[cutadapt_issue(read(A+f"cutadapt/upstream/{f}")) for f in ("issue-ca1-absolute-errors-rounding.md","issue-ca2-max-ee-quality-base.md","issue-ca3-index-criterion.md","issue-ca4-prefilter-insertions.md")]
cp=pr_sections(read(A+"cutadapt/upstream/pr-bodies.md"))
repos["cutadapt"]=dict(owner="marcelm", repo="cutadapt", fork="cindykrafft/cutadapt", forked=True, base="main", template="bug_report.md",
  guide="Bug report template asks for: version, install method, command line, example read, produced vs expected output. CHANGES.rst entry per PR (add the issue number). One topic per PR. black 22.3.0 + flake8.",
  issues=[dict(id=f"CA{i+1}", title=t, body=b) for i,(t,b) in enumerate(ci)],
  prs=[dict(id=f"CA{i+1}", title=t, body=b, branch=br, needs=f"CA{i+1}") for i,((t,b),br) in enumerate(zip(cp,["fix/absolute-error-count","fix/max-ee-quality-base","fix/index-alignment-score","fix/prefilter-anchored-insertion"]))],
  order_note="File CA3 as an issue and wait for the maintainer's view before its PR: it changes which reads are called ambiguous.")
# ---- umap
t,b=title_body_titleline(read(A+"umap/upstream/issue-u1-disconnected-sigma-inf.md"))
ps=read(A+"umap/upstream/pr-body.md"); pt=re.search(r"^\*\*Title:\*\*\s*(.+)$", ps, re.M); pb=foot(ps[pt.end():].strip())
repos["umap"]=dict(owner="lmcinnes", repo="umap", fork="cindykrafft/umap", forked=True, base="master", template=None,
  guide="CONTRIBUTING.md only: search issues first, clear reproduction, PR references the issue, run black. No templates, no changelog convention.",
  issues=[dict(id="U1", title=t, body=b)], prs=[dict(id="U1", title=pt.group(1).strip(), body=pb, branch="fix/smooth-knn-dist-disconnected-floor", needs="U1")], order_note="")
# ---- cellphonedb
names=["issue-cpdb1-thread-duplicate-permutations.md","issue-cpdb2-pvalue-strict-inequality.md","issue-cpdb3-method1-threshold-ignored.md","issue-cpdb4-deconvoluted-subunit-means.md","issue-cpdb5-iterations-zerodivision.md","issue-cpdb6-scoring-pandas3.md"]
cpi=[title_body_titleline(read(A+"cellphonedb/upstream/"+n)) for n in names]
cpp=pr_sections(read(A+"cellphonedb/upstream/pr-bodies.md"))
repos["cellphonedb"]=dict(owner="ventolab", repo="CellphoneDB", fork="cindykrafft/CellphoneDB", forked=True, base="master", template=None,
  guide="HOLD (2026-09-08): #231 and PR #232 are unanswered, the two-unanswered cap; CPDB2 waits for a maintainer signal. No CONTRIBUTING, no templates, no changelog. CI: Python 3.8, flake8, pytest method_tests.py (needs the database download). Maintainer replies on prior issues #179 and #60 (p-value definition) could not be read from the audit session: read them before filing CPDB2.",
  issues=[dict(id=f"CPDB{i+1}", title=t, body=b) for i,(t,b) in enumerate(cpi)],
  prs=[dict(id="CPDB5", title=cpp[0][0], body=cpp[0][1], branch="fix/iterations-zero-progress-step", needs="CPDB5"), dict(id="CPDB6", title=cpp[1][0], body=cpp[1][1], branch="fix/scoring-pandas3-index", needs="CPDB6")],
  order_note="Only CPDB5 and CPDB6 carry patches (they change no result). CPDB1-4 change numbers and go as issues for the maintainers' decision first; last commit on master was 2025-06-06.")
# ---- scanpy (scrublet port)
si=[scanpy_issue(read(A+f"scrublet/upstream/scanpy/{f}")) for f in ("issue-sr1-knn-neighbour-count.md","issue-sr3-log-transform-order.md")]
sp=read(A+"scrublet/upstream/pr-bodies.md"); sp=sp[sp.index("## Scanpy"):]
sprs=[]
for m in re.finditer(r'^### PR \d+ — `[^`]+` — "(.+?)"\s*\n(.*?)(?=^### PR |\Z)', sp, re.S|re.M):
    sprs.append((m.group(1).strip(), foot(m.group(2).strip())))
assert len(sprs)==2, sprs
repos["scanpy"]=dict(owner="scverse", repo="scanpy", fork="cindykrafft/scanpy", forked=True, base="main", template="bug-report.yml",
  guide="Same rules as the earlier Scanpy filings: bug-report form (uv-runnable reproducer with inline metadata), Ruff, towncrier fragment renamed to <PR>.fix.md once the number exists, PR template with tests and release-note boxes. Both branches are already on the fork.",
  issues=[dict(id=f"SR{n}", title=t, description=d, code=c, traceback=tb, versions=v) for n,(t,d,c,tb,v) in zip((1,3), si)],
  prs=[dict(id="SR1", title=sprs[0][0], body=sprs[0][1], branch="fix/scrublet-knn-neighbour-count", needs="SR1"), dict(id="SR3", title=sprs[1][0], body=sprs[1][1], branch="fix/scrublet-log-transform-order", needs="SR3")],
  order_note="SR1 changes every doublet score, so its PR needs the pinned expectations in tests/test_scrublet.py regenerated on a host with data access (pbmc3k download); see the kit README.")
# ---- iqtree discussion
d=read(A+"iqtree/upstream/discussion-iq2-ufboot-cutoff.md")
dm=re.search(r"^(?:Title:|# )\s*(.+)$", d, re.M)
repos["iqtree"]=dict(owner="iqtree", repo="iqtree3", fork=None, forked=False, template=None,
  guide="No templates. Bugs go to Issues, everything else to Discussions; this is a design question, so it goes to Discussions. Two documentation patches for iqtree/iqtree.github.io are in the kit if you also fork that repo.",
  issues=[], prs=[], discussions=[dict(id="IQ2", title=dm.group(1).strip(), body=foot(strip_comment(d[dm.end():])))], order_note="")

# ---- round 2: fixed kit format (Title: line; ### PR n — `branch` — "title")
def r2_issue(path):
    s=read(path); m=re.search(r"^Title:\s*(.+)$", s, re.M); t=m.group(1).strip()
    body=foot(strip_comment(s[m.end():]))
    cm=re.search(r"[\(\[]\s*comment (?:on|for) (#\d+(?:\s*/\s*#\d+)*)\s*[\)\]]", t, re.I)
    existing=None
    if cm:
        existing=int(re.search(r"#(\d+)", cm.group(1)).group(1))
        t=(t[:cm.start()]+t[cm.end():]).strip().rstrip(" :—")
    return t, body, existing
def r2_prs(path):
    s=read(path); out=[]
    for m in re.finditer(r'^### PR (\d+) — `([^`]+)` — "(.+?)"\s*\n(.*?)(?=^### PR |\Z)', s, re.S|re.M):
        out.append(dict(n=int(m.group(1)), branch=m.group(2), title=m.group(3).strip(), body=foot(m.group(4).strip())))
    return out
def r2(key, owner, repo, base, template, guide, issue_files, pr_needs, order_note="", dir=None, no_prs=False, forked=False):
    key_dir = dir or key
    issues=[]
    for f in issue_files:
        iid=re.search(r"(?:issue|comment)-([a-z]+\d+)-", f).group(1).upper()
        t,b,ex=r2_issue(A+f"{key_dir}/upstream/{f}")
        d=dict(id=iid, title=t, body=b)
        if ex: d["existing"]=ex
        issues.append(d)
    prs=[]
    import os as _os
    for p,needs in zip(r2_prs(A+f"{key_dir}/upstream/pr-bodies.md") if (not no_prs and _os.path.exists(A+f"{key_dir}/upstream/pr-bodies.md")) else [], pr_needs):
        d=dict(id=needs, title=p["title"], body=p["body"], branch=p["branch"], needs=needs)
        ex=next((i.get("existing") for i in issues if i["id"]==needs), None)
        if ex: d["existing"]=ex
        prs.append(d)
    assert len(prs)==len(pr_needs), (key, len(prs), pr_needs)
    repos[key]=dict(owner=owner, repo=repo, fork=f"cindykrafft/{repo}", forked=forked, base=base, template=template, guide=guide, issues=issues, prs=prs, order_note=order_note)
r2("htseq","htseq","htseq","main","bug_report.md",
   "Markdown bug-report template (versions, description, minimal example, exact command); no CONTRIBUTING, PR template or linter; doc/history.rst is the changelog and stops at 2.0.9. No prior issue for either finding (nearest #99, #94, #96, #106, #80, #14).",
   ["issue-hc2-unmapped-mate-minaqual.md","issue-hc1-bam-reader-window.md"], ["HC2","HC1"])
# deepTools: 4.0.0 kit (upstream-4.0.0/) after the 2026-09-04 rewrite; the 3.5.6 kit stays on disk as the record
_dt=A+"deeptools/upstream-4.0.0/"
_dt_issues=[]
for f,iid in (("comment-dt1-1108-1130.md","DT1"),("comment-dt4-1118.md","DT4"),("issue-dt5-bpm-is-cpm.md","DT5")):
    t,b,ex=r2_issue(_dt+f); d=dict(id=iid,title=t,body=b)
    if ex and iid!="DT1": d["existing"]=ex   # DT1: its threads #1108/#1130 were closed on 2026-09-05; it needs a fresh issue
    _dt_issues.append(d)
_dt_prs=[]
for p,needs in zip(r2_prs(_dt+"pr-bodies.md"),["DT1","DT4","DT3","DT8","DT9"]):
    d=dict(id=needs,title=p["title"],body=p["body"],branch=p["branch"],needs=needs)
    ex=next((i.get("existing") for i in _dt_issues if i["id"]==needs),None)
    if ex: d["existing"]=ex
    _dt_prs.append(d)
# new-on-4.0.0 defects (pre-release reports): upstream-4.0.0/new/
_dn=_dt+"new/"
for f,iid in (("issue-bamcompare-operations.md","DTN1"),("issue-plotpca-loadings.md","DTN2"),("issue-computematrixoperations-sort-group.md","DTN3")):
    t,b,ex=r2_issue(_dn+f); _dt_issues.append(dict(id=iid,title=t,body=b))
_pb=read(_dn+"pr-body.md")
for m,needs in zip(re.finditer(r'^### PR [A-C] — `([^`]+)` — "(.+?)"\s*\n(.*?)(?=^### PR |\Z)', _pb, re.S|re.M), ["DTN1","DTN2","DTN3"]):
    body=m.group(3).strip(); body=re.sub(r"^Title:.*\n\s*","",body,count=1)
    _dt_prs.append(dict(id=needs,title=m.group(2).strip(),body=foot(body),branch=m.group(1),needs=needs))
repos["deeptools"]=dict(owner="deeptools",repo="deepTools",fork="cindykrafft/deepTools",forked=True,base="master",template=None,
  guide="Markdown issue checklist and four-checkbox PR template; flake8 + pytest + cargo test on the 4.0.0 tree (Rust backend, Python in pydeeptools/). All patches here are against 4.0.0 master (branches fix4/* on the fork, made on 6f939b0). The maintainers closed #1108, #1130 and #1423 on 2026-09-05 with the 4.0.0 merge; #1118 (MNase) is still open. PyPI still ships 3.5.6.",
  issues=_dt_issues,prs=_dt_prs,
  order_note="4.0.0 is unreleased and being worked on today, so the two pre-release reports go first: DTN1 (bamCompare --operation first/second/add/mean write the log2 track) and DTN2 (plotPCA writes per-bin scores, not loadings), issue then PR each. The DT4 comment + PR on the open #1118 is exempt from the cap. DT8, DT1 (needs a fresh issue), DT3, DT5, DT9, DTN3 and the #1423 residual are held until a reply.")
r2("samtools","samtools","samtools","develop","bug_report.md",
   "CONTRIBUTING.md (new in 1.24) accepts AI-assisted work on conditions: every generated line reviewed by the submitter; an `Assisted-by: Claude:claude-fable-5-1` trailer on each commit and in the PR body; NO Signed-off-by from an agent (the DCO sign-off must be yours, real name); the commit message and PR description written by a human. The branch is already pushed to cindykrafft/samtools with the trailer and no sign-off: before opening the PR, `git fetch` it, rewrite the commit message in your own words and `git commit --amend -s`, then force-push the branch (or send me the message you want and I will amend it and add your Signed-off-by line at your instruction). Markdown bug-report template (3 headings), no PR template, NEWS.md bullet per change, `make test`. No prior issue for ST1 (nearest #1003, #640, #969). Fork exists; branch pushed.",
   ["issue-st1-stats-cov-ring-buffer.md"], ["ST1"], forked=True,
   order_note="ST1 filed 2026-09-08 as #2378 with PR #2379 (commit signed off by the submitter per the DCO). Waiting for the maintainers; nothing else to file here.")
r2("edger","bioc","edgeR","devel",None,
   "No tracker, no PRs: bioc/edgeR is a read-only mirror. The channel is the Bioconductor support site (support.bioconductor.org, tag edgeR) or the maintainers' e-mail; the 'issue' text below is the support-site post with the reproducible example, and the two patches (devel; RELEASE_3_23 with --keep-cr) are attached as diffs for the maintainers to apply. Search the support site for filterByExpr first (unreachable from the audit session). No fork applies.",
   ["issue-eg3-filterbyexpr-boundary.md"], [], no_prs=True,
   order_note="EG3 is real on every version but small (about four genes per twenty thousand on the cutoff); a support-site post is cheap and the fix is one line. The two offset bugs found (EG1, EG2) are already fixed upstream and are not to be raised.")
r2("lme4","lme4","lme4","master",None,
   "README: issues for bugs, PRs welcome but open an issue first; no templates, no linter; NEWS in inst/NEWS.Rd; testthat. Fork exists; all three branches pushed. LM2 goes as a comment on the maintainer's own open #867 (0 comments) with patch 0003 as the PR; LM1 is a pre-release report on master's new disp_dof_correction default (patch 0002); LM3 is a warning-text nit (patch 0001).",
   ["comment-lm2-hessian-se-867.md","issue-lm1-gamma-loglik-phi.md","issue-lm3-checkconv-component.md"], ["LM3","LM1","LM2"], forked=True,
   order_note="LM2 posted 2026-09-08 as a comment on #867 with PR #1000. lme4 now has two unanswered filings; LM1 (worth a heads-up before the 2.x release) and LM3 wait for a reply.")
r2("clusterprofiler","YuLab-SMU","clusterProfiler","devel","bug_report.md",
   "CONTRIBUTING.md: reproducible example with dput in a fresh session; markdown issue template (latest release, docs read, reproducible example; questions go to Bioconductor support/Biostars). The maintainer's 'how to bug author' guide and book were unreachable from the audit session: read them before posting. #819 read in full 2026-09-08 (thread-819.txt): the maintainer already named the CP5 cause and fix on 2026-06-22, so CP5 is dropped. CP1 is a heads-up only: fixed on devel, waiting for enrichit 0.2.2 to reach CRAN.",
   ["issue-cp1-gsea-table-rawp.md"], [], no_prs=True,
   order_note="Nothing to post here: CP5 dropped after reading #819 (already answered by the maintainer). CP1 is held: fixed and announced upstream. CP2/CP3/CP6/CP7 are fixed at master; CP8 is a design question.")
r2("enrichit","YuLab-SMU","enrichit","devel",None,
   "clusterProfiler's enrichment engine since 4.20 (CRAN package). No templates, NEWS + testthat. CP4 is a non-default option (gsea(method='sample'/'permute', adaptive=TRUE)) whose p-values are about half the GSEA convention; issue + git am-able patch with an exact-enumeration test. Fork exists; branch pushed.",
   ["issue-cp4-enrichit-sample-pvalue.md"], ["CP4"], dir="clusterprofiler", forked=True,
   order_note="Held: a rare option. File after a positive signal on the clusterProfiler thread.")
r2("gsea","GSEA-MSigDB","gsea-desktop","master",None,
   "CONTRIBUTING.md is the only contributing document: search the tracker first, include an executable test case, one focused problem per PR. No .github directory at all (no issue or PR template), no changelog file, no AI policy, no linter, and no wired-up test task in build.gradle (the JUnit jars sit unused). Tiny tracker (16 issues, 2017-2022); no prior report of either finding (nearest #5, #14, #26, #42, #50). Released binaries could not be downloaded (two Broad domains are blocked by the proxy), so every version was built from its tag; master and the v4.4.0 release tag differ only in a readme. Fork GSEA-MSigDB/gsea-desktop for the PRs.",
   ["issue-gs1-weighted-p15-negative-scores.md","issue-gs2-set-size-filter-equal-bounds.md"], ["GS1","GS2"],
   order_note="GS1 first and alone: the highest-cited package of the round (720 papers) returning an enrichment score of the wrong sign, and on two older releases outside the legal range. GS2 follows once GS1 has an answer.")
r2("bcftools","samtools","bcftools","develop",None,
   "CONTRIBUTING.md is the samtools document verbatim, so the samtools rules apply again: a real-name DCO sign-off that an agent may not add, an `Assisted-by:` trailer on the commit and in the PR body, and a human-written commit message and PR description. The kit's patch carries the trailer and no sign-off: after `git am`, rewrite the message in your own words and `git commit --amend -s`. No issue or PR template; NEWS bullets under `* bcftools <command>`; `make test` runs 2,480 tests (green before and after the patch, and the new test fails 2 of 4 checks without it). No prior report (nearest #897, #962, #1930, #1767, #2185).",
   ["issue-bf1-mwu-bias-int-overflow.md"], ["BF1"],
   order_note="One filing only. Note the exposure: the annotation does not exist in 1.9 or 1.10.2, the cohort's two most-cited versions, so this bites 1.13 onward.")
r2("star","alexdobin","STAR","master",None,
   "CONTRIBUTING.md is the only contributing document: questions go to the rna-star Google group rather than the tracker, and a bug report needs the exact command, copy-pasteable snippets, Log.out, observed vs expected and system information. PRs must state their purpose and guarantee that default behaviour does not change. No issue or PR template, no .github directory, no CI and no test suite, so the kit's patch adds the first executable regression test in the tree (2 failures on unmodified master, 2 passes with it). CHANGES.md bullets are the changelog convention. No prior report across five phrasings; the nearest open issue (#1922, five comments, unreadable from the session) is a different bug in the same area. The fork could not be resolved from the session: re-check the declines-AI topic before sending.",
   ["issue-st1-strandless-transcript-strand.md"], ["ST1"],
   order_note="Issue first; the PR is offered in the issue's last line rather than opened unsolicited, as CONTRIBUTING asks.")
r2("trimmomatic","usadellab","Trimmomatic","main",None,
   "No contributing document, no issue or PR template, no code of conduct and no linter; the changelog is versionHistory.txt (`Fix:` / `Feature:` lines), whose newest entry is another fix to the same class. CI runs `mvn -B clean verify` on every push and PR to `main`. The maintainers answered issues up to #88 (2026-07-01); the exact open-issue count could not be read from the session. No prior report across seven phrasings; #52 and #56 are nearby and their comments must be read before filing. No fork exists, so the declines-AI topic could not be checked.",
   ["issue-tc1-palindrome-integer-penalty.md"], ["TC1"],
   order_note="Issue first, then the PR: the fix is two characters plus a regression test (259 tests green before, 263 after; the new test fails on unmodified main).")
r2("limma","bioc","limma","devel",None,
   "No tracker and no PRs: bioc/limma is a read-only mirror. The channel is the Bioconductor support site (tag limma) or the maintainer's e-mail, and both are unreachable from the audit session, so searching the support site for prior reports is step 1 and yours to do. The text below is the support-site post; the two patches (devel C kernel, and RELEASE_3_23 R) are attached as diffs for the maintainers to apply. No fork applies.",
   ["issue-l1-arrayweights-reml-convergence.md"], [], no_prs=True,
   order_note="Worth sending before limma 4.0.0: no released default path reaches the REML weighting code, but devel's new voomLmFit(sample.weights=TRUE) calls it directly and reproduces the unconverged answer exactly.")
r2("featurecounts","ShiLab-Bioinformatics","subread","master",None,
   "The developers' GitHub mirror of Subread (release channel is SourceForge; user forum is the Subread Google Group; Rsubread goes to Bioconductor support). The GitHub tracker could not be read from the audit session (search returns nothing for the repo): check whether the maintainers answer issues there before sending anything. No CONTRIBUTING, templates, changelog or linter; tests are shell scripts with .ora expectations. FC2 changes numbers only for mixed single-end/paired-end libraries under stranded counting; FC1 is a rare option. Both patches add a test that fails on unmodified master.",
   ["issue-fc2-read-type-filter.md","issue-fc1-splitonly-singletons.md"], ["FC1","FC2"],
   order_note="Both held. If the maintainers do use the GitHub tracker, FC2 goes first as an issue (a 2.0.2 regression against the manual's own sentence), PR after their view.")
r2("fieldtrip","fieldtrip","fieldtrip","master",None,
   "PRs against master from a fork; no issue template. Five PRs and two issues are up already (the maintainer, schoffelen, is active on them: #2613 merged, #2610 carries his own commits). FT12 is the issue he asked for on #2610; FT13 and FT14 are replies on threads he wrote in, so they are exempt from the two-unanswered cap.",
   ["issue-ft12-dpss-hack-two-outputs.md","issue-ft13-reply-2610-tests.md","issue-ft14-reply-2609-edge-bins.md","issue-ft15-reply-2610-bandwidth.md","issue-ft16-reply-2614-scope.md"], [],
   order_note="FT12-FT14 are posted. FT15 answers his 2026-09-07 question on #2610 (the +1 as a bandwidth term; he says the PR is almost ready to merge). FT16 answers his two 2026-09-07 comments on #2614 (minor issue; FAQ draft in the kit; Octave survey offered).")
r2("bedtools","arq5x","bedtools2","master",None,
   "HOLD (2026-09-08): PR #1143, PR #1144 and the #1142 comment are unanswered, which is the two-unanswered cap; BT1 waits for a maintainer signal. No CONTRIBUTING, templates, linter or changelog convention; CI is make test; docs/content/history.rst is a hand-edited per-release changelog. BT2 is a comment on open #1142; BT1 relates to open #673 (2018, same defect); BT6 relates to #1089. All five change published numbers, so open the issue and wait for a signal before the PR. BT3 and BT5 are issues only (their fixes need invasive changes).",
   ["issue-bt1-coverage-split-count.md","issue-bt2-intersect-split-F.md","issue-bt3-closest-tie-order.md","issue-bt4-large-chrom-coordinates.md","issue-bt5-pct-float-truncation.md"],
   ["BT1","BT2","BT4"])
r2("fastp","OpenGene","fastp","master",None,
   "HOLD (owner, 2026-09-05): fastp is up to date for now, PR #715 unanswered; FP1-FP3 wait. No CONTRIBUTING, templates, changelog or linter; CI builds and smoke-tests; ./fastp test and scripts/*.sh are the test conventions (PR 2 adds a script in that style). FP1 and FP3 are comments on open #474 and #518 (both 2023); #474 has one comment that could not be read from the audit session, read it before posting. FP2 is new.",
   ["issue-fp1-cut-window-trim-front.md","issue-fp2-known-adapter-over60.md","issue-fp3-indel-adapter-offset.md"], ["FP1","FP2","FP3"])
r2("plink","chrchang","plink-ng","master",None,
   "No CONTRIBUTING, templates, changelog or linter; PLINK 1.9 has no unit-test runner (1.9/tests needs a PLINK 1.07 build), so the PR carries its own exhaustive driver. No prior issue (nearest #128); several other audit-style issues (#341, #353, #363, #365) landed 2026-08-31 to 09-02, so read those first to avoid a duplicate. PLINK 2.0 is unaffected: the fix is to 1.9/plink_stats.c only.",
   ["issue-pl1-hwe-threshold-boundary.md"], ["PL1"])

# ---- triage (2026-09-03): file only findings that change published numbers under default/common settings; at most two per repo until a maintainer responds
TIER={"filed":{"DT1":"comment on #1108 (closed 2026-09-05)","CA1":"#892 / PR #893","U1":"#1286 / PR #1287 (merged 2026-09-05)","CPDB1":"#231","DTN1":"#1457 / PR #1458","DTN2":"#1459 / PR #1460","BT2":"comment on #1142 / PR #1144 (2026-09-05)","FT12":"#2614 (2026-09-05)","FT13":"posted on PR #2610 (2026-09-05)","FT14":"posted on #2609 (2026-09-05)","FT15":"posted on PR #2610 (2026-09-07, per the comment count)","FT16":"posted on #2614 (2026-09-07, per the comment count)","PL1":"#380 / PR #381 (closed 2026-09-03: the maintainer applied his own equivalent fix, 1fe42e5)","DT4":"comment on #1118 / PR #1466 (2026-09-08)","ST1":"#2378 / PR #2379 (2026-09-08)","LM2":"comment on #867 / PR #1000 (2026-09-08)"},
      "now":["HC2","EG3","GS1","BF1","ST1","TC1","L1"],
      "comment":[]}
def tier_of(i):
    if i in TIER["filed"]: return "filed"
    if i in TIER["now"]: return "now"
    if i in TIER["comment"]: return "comment"
    return "held"
for r in repos.values():
    for i in r["issues"]:
        i["tier"]=tier_of(i["id"]); 
        if i["tier"]=="filed": i["filed_as"]=TIER["filed"][i["id"]]
    for p in r["prs"]:
        p["tier"]=tier_of(p["needs"])
        if p["tier"]=="filed": p["filed_as"]=TIER["filed"][p["needs"]]
    for d in r.get("discussions",[]): d["tier"]="held"
for k in ("htseq","deeptools","bedtools","fastp","plink","fieldtrip"): repos[k]["forked"]=True
# repositories whose maintainers decline AI-generated contributions (topic on the fork; mirrored in site/audits.json)
import json as _j
_cfg=_j.load(open(ROOT+"/site/audits.json"))
_declined={a["dir"] for a in _cfg["audits"] if a.get("declines_ai")}
for k,r in repos.items():
    r["declines_ai"]= k in _declined or (k=="scanpy" and "scanpy" in _declined)

# ---- issue fixes (README step 6): audits/<pkg>/issue-fixes/<n>-<slug>/
import glob, os
UP={"spm":("spm","spm","main"),"fieldtrip":("fieldtrip","fieldtrip","master"),"afni":("afni","afni","master"),"freesurfer":("freesurfer","freesurfer","dev"),
    "kilosort":("MouseLand","Kilosort","main"),"suite2p":("MouseLand","suite2p","main"),"scanpy":("scverse","scanpy","main"),"umap":("lmcinnes","umap","master"),
    "cutadapt":("marcelm","cutadapt","main"),"cellphonedb":("ventolab","CellphoneDB","master"),"plink":("chrchang","plink-ng","master"),"deeptools":("deeptools","deepTools","master"),
    "bedtools":("arq5x","bedtools2","master"),"fastp":("OpenGene","fastp","master"),"iqtree":("iqtree","iqtree3","master"),"macs2":("macs3-project","MACS","main")}
FORK={"spm":"cindykrafft/spm","fieldtrip":"cindykrafft/fieldtrip","afni":"cindykrafft/afni","freesurfer":"cindykrafft/freesurfer","kilosort":"cindykrafft/Kilosort","suite2p":"cindykrafft/suite2p",
      "scanpy":"cindykrafft/scanpy","umap":"cindykrafft/umap","cutadapt":"cindykrafft/cutadapt","cellphonedb":"cindykrafft/CellphoneDB","plink":"cindykrafft/plink-ng","deeptools":"cindykrafft/deepTools",
      "bedtools":"cindykrafft/bedtools2","fastp":"cindykrafft/fastp","iqtree":"cindykrafft/iqtree3","macs2":"cindykrafft/MACS"}
PUSHED=set(open(ROOT+"/site/pushed-branches.txt").read().split()) if os.path.exists(ROOT+"/site/pushed-branches.txt") else set()
# replies drafted for a thread and not yet posted by the owner
PENDING_REPLY={("iqtree",198)}
FILED={}
for line in open(ROOT+"/site/filed-fixes.txt"):
    line=line.strip()
    if not line or line.startswith("#"): continue
    pkg,issue,what,num,state=line.split(":"); FILED[(pkg,int(issue))]=dict(what=what,num=int(num),state=state)
fixes=[]
for d in sorted(glob.glob(A+"*/issue-fixes/*/")):
    pkg=d.split("/audits/")[1].split("/")[0]; slug=os.path.basename(d.rstrip("/")); n=int(slug.split("-")[0])
    if not (os.path.exists(d+"pr-body.md") and os.path.exists(d+"README.md") and glob.glob(d+"0001-*.patch")): continue
    pb=read(d+"pr-body.md"); m=re.search(r"^Title:\s*(.+)$", pb, re.M); title=m.group(1).strip(); body=foot(pb[m.end():].strip())
    cm=read(d+"comment.md") if os.path.exists(d+"comment.md") else ""
    # the kit's internal "Title: ..." first line is never part of what gets pasted
    cm=re.sub(r"\A\s*Title:[^\n]*\n+", "", cm)
    patches=sorted(glob.glob(d+"0001-*.patch")); branch=None
    rm=re.search(r"`(fix/issue-\d+[^`]*)`", read(d+"README.md")) if os.path.exists(d+"README.md") else None
    branch=rm.group(1) if rm else f"fix/issue-{n}"
    o,r,base=UP[pkg]; fork=FORK[pkg]
    pushed=[p.split(":",1)[1] for p in PUSHED if p.split(":",1)[0]==fork.split("/")[1] and p.split(":",1)[1].startswith(f"fix/issue-{n}")]
    if pushed: branch=pushed[0]
    assigned=read(d+"assigned.txt").strip() if os.path.exists(d+"assigned.txt") else ""
    fixes.append(dict(comment_pending=((pkg,n) in PENDING_REPLY), filed=FILED.get((pkg,n)), stale=(pkg in STALE_OFF), pkg=pkg, owner=o, repo=r, base=base, fork=fork, assigned=assigned, forked=(fork.split("/")[1]+":"+branch) in PUSHED, issue=n, title=title, body=body, comment=foot(cm.strip()) if cm.strip() else "", branch=branch,
                      declines=(pkg in _declined)))
json.dump(fixes, open(os.path.join(OUT,"fixes.json"),"w"), indent=1)
# ---- ordered action list (2026-09-08): what to do next, top first; everything else waits for a signal
ACTIONS=[
 dict(kind="issue", key="gsea", id="GS1", why="round 4's strongest finding and the most-cited package audited so far (720 papers): the weighted_p1.5 scoring scheme raises a signed metric to a fractional power, so every negatively ranked gene contributes a fallback constant; a hand-computable case returns -1.000 for a true -0.706, two older releases return -1.500, and a real gene set flips sign"),
 dict(kind="pr", key="gsea", id="GS1", why="the fix with a regression test that fails on unmodified master; fork GSEA-MSigDB/gsea-desktop first"),
 dict(kind="issue", key="bcftools", id="BF1", why="mpileup's Mann-Whitney bias annotations overflow a 32-bit accumulator at 1291 reads in one bin, always downward: a 1500-read site reports MQBZ -5.76 for a true -23.98, and 41 of 160 realistic pileups flip the usual MQBZ < -3 filter from drop to keep"),
 dict(kind="pr", key="bcftools", id="BF1", why="the 64-bit fix plus test/test-mwu.c; the samtools AI policy applies, so rewrite the commit message yourself and add your own sign-off (git commit --amend -s), never a sign-off from an agent"),
 dict(kind="issue", key="star", id="ST1", why="a GTF feature with '.' in the strand column makes TranscriptomeSAM transform coordinates as plus and set the flag as minus (every flag inverted, 1524 sequence mismatches against zero), and stranded STARsolo counts such genes as zero; issue first, PR offered in its last line as CONTRIBUTING asks"),
 dict(kind="issue", key="trimmomatic", id="TC1", why="ILLUMINACLIP's palindrome mode computes the per-mismatch penalty with integer division, so mismatches below Q10 cost nothing; the error is one-sided, so pairs below the threshold are clipped anyway and the reverse read is dropped (1.2 percent of 4000 synthetic pairs)"),
 dict(kind="pr", key="trimmomatic", id="TC1", why="two characters plus a regression test (259 tests green before, 263 after); fork usadellab/Trimmomatic first"),
 dict(kind="issue", key="limma", id="L1", why="a Bioconductor support-site post, not a GitHub issue: arrayWeights' REML path divides its convergence criterion by the gene count twice and stops after one to three iterations; no released default path reaches it, but devel's voomLmFit(sample.weights=TRUE) does, so this is worth sending before limma 4.0.0"),
 dict(kind="fix", pkg="iqtree", issue=198, why="reply on PR #214 (drafted, needs your approval): the maintainer asked for the CI additions to be removed, so the branch is now code-only (force-pushed, commit 04f81848) and the reproduction moves into the thread; the comment text is in the card below"),
 dict(kind="issue", key="edger", id="EG3", why="support-site post, not a GitHub issue: filterByExpr drops a gene sitting exactly on the CPM cutoff by one ulp, every version, one-line fix attached; small effect, so post only if you are comfortable with a low-magnitude report"),
]
WAITING=[
 ("GSEA GS2 (set_min == set_max skips the size filter and can abort the run)", "an answer on GS1: same repository, two-filing cap"),
 ("STAR N1/N2 (soft-clip extension drops short-overhang reads; undocumented N_unmapped rows)", "a maintainer signal on ST1"),
 ("Trimmomatic N1-N9 (MAXINFO aborts over 1000 nt, N scored as Q0, TRAILING never examines base 0, SLIDINGWINDOW cut position vs the manual)", "a maintainer signal on TC1; several are documentation rather than wrong numbers"),
 ("BCFtools N1/N2 (undocumented PSC average-depth denominator; DP=0 genotypes omitted from the DP distribution)", "a maintainer signal on BF1"),
 ("limma N1-N7 (contrasts.fit approximation under voom weights, topTable/decideTests cutoff convention, cyclicloess default iterations)", "a reply on the L1 support-site post"),
 ("lme4 LM1 (master-only Gamma logLik dispersion mismatch), LM3", "a reply on the #867 comment or PR #1000 (both filed 2026-09-08, the two-unanswered cap); LM1 is a pre-release heads-up worth sending before 2.x ships"),
 ("enrichit CP4 (sample-permutation p-values halved, rare option)", "the owner's call: #819 shows the maintainer fixing enrichit reports within weeks, so CP4 could go straight to YuLab-SMU/enrichit as issue + PR (branch on the fork) without waiting for a signal on a clusterProfiler thread"),
 ("featureCounts FC2 (read-type filter lost in 2.0.2), FC1", "confirmation that the maintainers answer GitHub issues on ShiLab-Bioinformatics/subread"),
 ("clusterProfiler CP1 (release GSEA table filtered on raw p)", "never as a report: fixed on devel; a heads-up only if enrichit 0.2.2 is slow to reach CRAN"),
 ("BEDTools BT1 (coverage -split counts blocks)", "a reply on #1142, PR #1143 or PR #1144 (cap reached)"),
 ("CellPhoneDB CPDB2 (p-value ties, p = 0)", "a reply on #231 or PR #232 (cap reached)"),
 ("fastp FP2 (adapter over 60 bases), FP1, FP3", "owner's hold of 2026-09-05; PR #715 unanswered"),
 ("Scanpy #3809 fix, SR1/SR3 (Scrublet port)", "a reply on PR #4337 or #4336"),
 ("Kilosort #1039 fix", "a reply on PR #1043, PR #1045 or issues #1044/#1046/#1047"),
 ("Suite2p #1079 (assigned upstream; comment only)", "a reply on PR #1266-#1268 or issues #1265/#1269/#1270"),
 ("FieldTrip #2345 fix", "#2608, #2610, #2611 or #2612 merged or answered (#2610 is 'almost ready to merge')"),
 ("deepTools DT1, DT5, DT8, DT9, DTN3", "a reply on #1457/#1458, #1459/#1460 or PR #1466"),
 ("SPM and AFNI second fixes", "not chosen yet; their first fixes were merged, so they are next to prepare"),
 ("umap third fix, IQ-TREE third fix", "PR #1288 / PR #210 answered"),
 ("HTSeq HC1/HC2, FreeSurfer #1358", "never: the maintainers decline AI-generated contributions"),
]
json.dump(dict(actions=ACTIONS, waiting=WAITING), open(os.path.join(OUT,"actions.json"),"w"), indent=1)
print("issue fixes:", [(f["pkg"], f["issue"], f["forked"]) for f in fixes])
for k,msg in {}.items():
    if k in repos:
        repos[k]["order_note"]=msg; repos[k]["stale"]=True
        for p in repos[k]["prs"]:
            if p["tier"]!="filed": p["tier"]="held"
json.dump(repos, open(os.path.join(OUT,"data.json"),"w"), indent=1)
enc=lambda s: u.quote(s, safe="-_.!~*'()")
for k,r in repos.items():
    for i in r["issues"]:
        if "description" in i: n=len(enc(i["title"]))+len(enc(i["description"]))+len(enc(i["code"]))+len(enc(i["traceback"]))+len(enc(i["versions"]))
        else: n=len(enc(i["title"]))+len(enc(i["body"]))
        print(f"{k:12} {i['id']:6} prefill length ~{n+80}")
    for p in r["prs"]: print(f"{k:12} PR {p['id']:5} ~{len(enc(p['title']))+len(enc(p['body']))+80}")
