import json, re, os, urllib.parse as u
ROOT=os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
A=ROOT+"/audits/"
OUT=os.path.join(os.path.dirname(os.path.abspath(__file__)), "out"); os.makedirs(OUT, exist_ok=True)
FOOTER="\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
def foot(b): return b if "Generated by [Claude Code]" in b else b.rstrip()+FOOTER
def strip_comment(s): return re.sub(r"<!--.*?-->\s*", "", s, count=1, flags=re.S).strip()
def read(p): return open(p, encoding="utf-8").read()
def title_body_titleline(s):
    m=re.search(r"^Title:\s*(.+)$", s, re.M); t=m.group(1).strip()
    body=s[m.end():]; return t, foot(strip_comment(body))
def cutadapt_issue(s):
    m=re.search(r"^\*\*Title:\*\*\s*(.+)$", s, re.M); t=m.group(1).strip()
    body=s[m.end():].strip(); return t, foot(body)
def scanpy_issue(s):
    t=re.search(r"^# Bug report:\s*(.+)$", s, re.M).group(1).strip()
    desc=re.search(r"\*\*What happened\?\*\*\s*(.*?)\*\*Minimal code sample\*\*", s, re.S).group(1).strip()
    code=re.search(r"\*\*Minimal code sample\*\*.*?```python\n(.*?)```", s, re.S).group(1)
    tb=re.search(r"\*\*Error output\*\*\s*(.*?)\*\*Versions\*\*", s, re.S).group(1).strip()
    tb=re.sub(r"^```\w*\n|\n```$", "", tb.strip()).strip()
    ver=s[s.index("**Versions**")+len("**Versions**"):].strip()
    return t, foot(desc), code, tb, ver
def pr_sections(s):
    out=[]
    for m in re.finditer(r"^## (PR \d+[^\n]*)\n(.*?)(?=^## |\Z)", s, re.S|re.M):
        sec=m.group(2); tm=re.search(r"^\*\*Title:\*\*\s*(.+)$", sec, re.M)
        if not tm: continue
        out.append((tm.group(1).strip(), foot(sec[tm.end():].strip())))
    return out
repos={}
# ---- stale bases: upstream rewrote its tree after the kit was made; nothing files until re-verified
STALE_OFF={"deeptools":"deepTools squash-merged its 4.0.0 rewrite into master on 2026-09-04 (4db9d816: Rust backend, Python moved to pydeeptools/). Every patch here was made against 3.5.6 and no longer applies; PyPI still ships 3.5.6. Re-verification against 4.0.0 is in progress; file nothing from this section until it lands."}
# ---- cutadapt
ci=[cutadapt_issue(read(A+f"cutadapt/upstream/{f}")) for f in ("issue-ca1-absolute-errors-rounding.md","issue-ca2-max-ee-quality-base.md","issue-ca3-index-criterion.md","issue-ca4-prefilter-insertions.md")]
cp=pr_sections(read(A+"cutadapt/upstream/pr-bodies.md"))
repos["cutadapt"]=dict(owner="marcelm", repo="cutadapt", fork="cindykrafft/cutadapt", forked=True, base="main", template="bug_report.md",
  guide="Bug report template asks for: version, install method, command line, example read, produced vs expected output. CHANGES.rst entry per PR (add the issue number). One topic per PR. black 22.3.0 + flake8.",
  issues=[dict(id=f"CA{i+1}", title=t, body=b) for i,(t,b) in enumerate(ci)],
  prs=[dict(id=f"CA{i+1}", title=t, body=b, branch=br, needs=f"CA{i+1}") for i,((t,b),br) in enumerate(zip(cp,["fix/absolute-error-count","fix/max-ee-quality-base","fix/index-alignment-score","fix/prefilter-anchored-insertion"]))],
  order_note="File CA3 as an issue and wait for the maintainer's view before its PR: it changes which reads are called ambiguous.")
# ---- umap
t,b=title_body_titleline(read(A+"umap/upstream/issue-u1-disconnected-sigma-inf.md"))
ps=read(A+"umap/upstream/pr-body.md"); pt=re.search(r"^\*\*Title:\*\*\s*(.+)$", ps, re.M); pb=foot(ps[pt.end():].strip())
repos["umap"]=dict(owner="lmcinnes", repo="umap", fork="cindykrafft/umap", forked=True, base="master", template=None,
  guide="CONTRIBUTING.md only: search issues first, clear reproduction, PR references the issue, run black. No templates, no changelog convention.",
  issues=[dict(id="U1", title=t, body=b)], prs=[dict(id="U1", title=pt.group(1).strip(), body=pb, branch="fix/smooth-knn-dist-disconnected-floor", needs="U1")], order_note="")
# ---- cellphonedb
names=["issue-cpdb1-thread-duplicate-permutations.md","issue-cpdb2-pvalue-strict-inequality.md","issue-cpdb3-method1-threshold-ignored.md","issue-cpdb4-deconvoluted-subunit-means.md","issue-cpdb5-iterations-zerodivision.md","issue-cpdb6-scoring-pandas3.md"]
cpi=[title_body_titleline(read(A+"cellphonedb/upstream/"+n)) for n in names]
cpp=pr_sections(read(A+"cellphonedb/upstream/pr-bodies.md"))
repos["cellphonedb"]=dict(owner="ventolab", repo="CellphoneDB", fork="cindykrafft/CellphoneDB", forked=True, base="master", template=None,
  guide="HOLD (2026-09-08): #231 and PR #232 are unanswered, the two-unanswered cap; CPDB2 waits for a maintainer signal. No CONTRIBUTING, no templates, no changelog. CI: Python 3.8, flake8, pytest method_tests.py (needs the database download). Maintainer replies on prior issues #179 and #60 (p-value definition) could not be read from the audit session: read them before filing CPDB2.",
  issues=[dict(id=f"CPDB{i+1}", title=t, body=b) for i,(t,b) in enumerate(cpi)],
  prs=[dict(id="CPDB5", title=cpp[0][0], body=cpp[0][1], branch="fix/iterations-zero-progress-step", needs="CPDB5"), dict(id="CPDB6", title=cpp[1][0], body=cpp[1][1], branch="fix/scoring-pandas3-index", needs="CPDB6")],
  order_note="Only CPDB5 and CPDB6 carry patches (they change no result). CPDB1-4 change numbers and go as issues for the maintainers' decision first; last commit on master was 2025-06-06.")
# ---- scanpy (scrublet port)
si=[scanpy_issue(read(A+f"scrublet/upstream/scanpy/{f}")) for f in ("issue-sr1-knn-neighbour-count.md","issue-sr3-log-transform-order.md")]
sp=read(A+"scrublet/upstream/pr-bodies.md"); sp=sp[sp.index("## Scanpy"):]
sprs=[]
for m in re.finditer(r'^### PR \d+ — `[^`]+` — "(.+?)"\s*\n(.*?)(?=^### PR |\Z)', sp, re.S|re.M):
    sprs.append((m.group(1).strip(), foot(m.group(2).strip())))
assert len(sprs)==2, sprs
repos["scanpy"]=dict(owner="scverse", repo="scanpy", fork="cindykrafft/scanpy", forked=True, base="main", template="bug-report.yml",
  guide="Same rules as the earlier Scanpy filings: bug-report form (uv-runnable reproducer with inline metadata), Ruff, towncrier fragment renamed to <PR>.fix.md once the number exists, PR template with tests and release-note boxes. Both branches are already on the fork.",
  issues=[dict(id=f"SR{n}", title=t, description=d, code=c, traceback=tb, versions=v) for n,(t,d,c,tb,v) in zip((1,3), si)],
  prs=[dict(id="SR1", title=sprs[0][0], body=sprs[0][1], branch="fix/scrublet-knn-neighbour-count", needs="SR1"), dict(id="SR3", title=sprs[1][0], body=sprs[1][1], branch="fix/scrublet-log-transform-order", needs="SR3")],
  order_note="SR1 changes every doublet score, so its PR needs the pinned expectations in tests/test_scrublet.py regenerated on a host with data access (pbmc3k download); see the kit README.")
# ---- iqtree discussion
d=read(A+"iqtree/upstream/discussion-iq2-ufboot-cutoff.md")
dm=re.search(r"^(?:Title:|# )\s*(.+)$", d, re.M)
repos["iqtree"]=dict(owner="iqtree", repo="iqtree3", fork=None, forked=False, template=None,
  guide="No templates. Bugs go to Issues, everything else to Discussions; this is a design question, so it goes to Discussions. Two documentation patches for iqtree/iqtree.github.io are in the kit if you also fork that repo.",
  issues=[], prs=[], discussions=[dict(id="IQ2", title=dm.group(1).strip(), body=foot(strip_comment(d[dm.end():])))], order_note="")

# ---- round 2: fixed kit format (Title: line; ### PR n — `branch` — "title")
def r2_issue(path):
    s=read(path); m=re.search(r"^Title:\s*(.+)$", s, re.M); t=m.group(1).strip()
    body=foot(strip_comment(s[m.end():]))
    cm=re.search(r"[\(\[]\s*comment (?:on|for) (#\d+(?:\s*/\s*#\d+)*)\s*[\)\]]", t, re.I)
    existing=None
    if cm:
        existing=int(re.search(r"#(\d+)", cm.group(1)).group(1))
        t=(t[:cm.start()]+t[cm.end():]).strip().rstrip(" :—")
    return t, body, existing
def r2_prs(path):
    s=read(path); out=[]
    for m in re.finditer(r'^### PR (\d+) — `([^`]+)` — "(.+?)"\s*\n(.*?)(?=^### PR |\Z)', s, re.S|re.M):
        out.append(dict(n=int(m.group(1)), branch=m.group(2), title=m.group(3).strip(), body=foot(m.group(4).strip())))
    return out
def r2(key, owner, repo, base, template, guide, issue_files, pr_needs, order_note="", dir=None, no_prs=False, forked=False):
    key_dir = dir or key
    issues=[]
    for f in issue_files:
        iid=re.search(r"(?:issue|comment)-([a-z]+\d+)-", f).group(1).upper()
        t,b,ex=r2_issue(A+f"{key_dir}/upstream/{f}")
        d=dict(id=iid, title=t, body=b)
        if ex: d["existing"]=ex
        issues.append(d)
    prs=[]
    import os as _os
    for p,needs in zip(r2_prs(A+f"{key_dir}/upstream/pr-bodies.md") if (not no_prs and _os.path.exists(A+f"{key_dir}/upstream/pr-bodies.md")) else [], pr_needs):
        d=dict(id=needs, title=p["title"], body=p["body"], branch=p["branch"], needs=needs)
        ex=next((i.get("existing") for i in issues if i["id"]==needs), None)
        if ex: d["existing"]=ex
        prs.append(d)
    assert len(prs)==len(pr_needs), (key, len(prs), pr_needs)
    repos[key]=dict(owner=owner, repo=repo, fork=f"cindykrafft/{repo}", forked=forked, base=base, template=template, guide=guide, issues=issues, prs=prs, order_note=order_note)
r2("htseq","htseq","htseq","main","bug_report.md",
   "Markdown bug-report template (versions, description, minimal example, exact command); no CONTRIBUTING, PR template or linter; doc/history.rst is the changelog and stops at 2.0.9. No prior issue for either finding (nearest #99, #94, #96, #106, #80, #14).",
   ["issue-hc2-unmapped-mate-minaqual.md","issue-hc1-bam-reader-window.md"], ["HC2","HC1"])
# deepTools: 4.0.0 kit (upstream-4.0.0/) after the 2026-09-04 rewrite; the 3.5.6 kit stays on disk as the record
_dt=A+"deeptools/upstream-4.0.0/"
_dt_issues=[]
for f,iid in (("comment-dt1-1108-1130.md","DT1"),("comment-dt4-1118.md","DT4"),("issue-dt5-bpm-is-cpm.md","DT5")):
    t,b,ex=r2_issue(_dt+f); d=dict(id=iid,title=t,body=b)
    if ex and iid!="DT1": d["existing"]=ex   # DT1: its threads #1108/#1130 were closed on 2026-09-05; it needs a fresh issue
    _dt_issues.append(d)
_dt_prs=[]
for p,needs in zip(r2_prs(_dt+"pr-bodies.md"),["DT1","DT4","DT3","DT8","DT9"]):
    d=dict(id=needs,title=p["title"],body=p["body"],branch=p["branch"],needs=needs)
    ex=next((i.get("existing") for i in _dt_issues if i["id"]==needs),None)
    if ex: d["existing"]=ex
    _dt_prs.append(d)
# new-on-4.0.0 defects (pre-release reports): upstream-4.0.0/new/
_dn=_dt+"new/"
for f,iid in (("issue-bamcompare-operations.md","DTN1"),("issue-plotpca-loadings.md","DTN2"),("issue-computematrixoperations-sort-group.md","DTN3")):
    t,b,ex=r2_issue(_dn+f); _dt_issues.append(dict(id=iid,title=t,body=b))
_pb=read(_dn+"pr-body.md")
for m,needs in zip(re.finditer(r'^### PR [A-C] — `([^`]+)` — "(.+?)"\s*\n(.*?)(?=^### PR |\Z)', _pb, re.S|re.M), ["DTN1","DTN2","DTN3"]):
    body=m.group(3).strip(); body=re.sub(r"^Title:.*\n\s*","",body,count=1)
    _dt_prs.append(dict(id=needs,title=m.group(2).strip(),body=foot(body),branch=m.group(1),needs=needs))
repos["deeptools"]=dict(owner="deeptools",repo="deepTools",fork="cindykrafft/deepTools",forked=True,base="master",template=None,
  guide="Markdown issue checklist and four-checkbox PR template; flake8 + pytest + cargo test on the 4.0.0 tree (Rust backend, Python in pydeeptools/). All patches here are against 4.0.0 master (branches fix4/* on the fork, made on 6f939b0). The maintainers closed #1108, #1130 and #1423 on 2026-09-05 with the 4.0.0 merge; #1118 (MNase) is still open. PyPI still ships 3.5.6.",
  issues=_dt_issues,prs=_dt_prs,
  order_note="4.0.0 is unreleased and being worked on today, so the two pre-release reports go first: DTN1 (bamCompare --operation first/second/add/mean write the log2 track) and DTN2 (plotPCA writes per-bin scores, not loadings), issue then PR each. The DT4 comment + PR on the open #1118 is exempt from the cap. DT8, DT1 (needs a fresh issue), DT3, DT5, DT9, DTN3 and the #1423 residual are held until a reply.")
r2("samtools","samtools","samtools","develop","bug_report.md",
   "CONTRIBUTING.md (new in 1.24) accepts AI-assisted work on conditions: every generated line reviewed by the submitter; an `Assisted-by: Claude:claude-fable-5-1` trailer on each commit and at the end of the PR body; NO Signed-off-by from an agent (the DCO sign-off must be yours, real name); the commit message and PR description written by a human. ST1 went through this way and was merged 2026-09-24. The ST3 branch fix/stats-dup-supplementary-isize-sd is on cindykrafft/samtools (two commits, 1776b17 + 47d3376 on develop de749a6) with the trailer and your Signed-off-by on both commits (added at your instruction 2026-09-24), ready for the PR. Markdown bug-report template (3 headings), no PR template, NEWS.md bullet per change, `make test`. The duplicate-count finding is the open maintainer question #696 (pd3, 2017, no comments), so it is a comment there, not a new issue, and the PR says Fixes #696.",
   ["issue-st1-stats-cov-ring-buffer.md","comment-st3-696-dup-supplementary.md"], ["ST1","ST3"], forked=True,
   order_note="ST1 (#2378 / PR #2379) merged 2026-09-24; ST3 filed 2026-09-24 as a comment on #696 + PR #2388. Nothing else here until the maintainers answer.")
r2("edger","bioc","edgeR","devel",None,
   "No tracker, no PRs: bioc/edgeR is a read-only mirror. The channel is the Bioconductor support site (support.bioconductor.org, tag edgeR) or the maintainers' e-mail; the 'issue' text below is the support-site post with the reproducible example, and the two patches (devel; RELEASE_3_23 with --keep-cr) are attached as diffs for the maintainers to apply. Search the support site for filterByExpr first (unreachable from the audit session). No fork applies.",
   ["issue-eg3-filterbyexpr-boundary.md"], [], no_prs=True,
   order_note="EG3 is real on every version but small (about four genes per twenty thousand on the cutoff); a support-site post is cheap and the fix is one line. The two offset bugs found (EG1, EG2) are already fixed upstream and are not to be raised.")
r2("lme4","lme4","lme4","master",None,
   "README: issues for bugs, PRs welcome but open an issue first; no templates, no linter; NEWS in inst/NEWS.Rd; testthat. Fork exists; all three branches pushed. LM2 goes as a comment on the maintainer's own open #867 (0 comments) with patch 0003 as the PR; LM1 is a pre-release report on master's new disp_dof_correction default (patch 0002); LM3 is a warning-text nit (patch 0001).",
   ["comment-lm2-hessian-se-867.md","issue-lm1-gamma-loglik-phi.md","issue-lm3-checkconv-component.md"], ["LM3","LM1","LM2"], forked=True,
   order_note="LM2 posted 2026-09-08 as a comment on #867 with PR #1000. lme4 now has two unanswered filings; LM1 (worth a heads-up before the 2.x release) and LM3 wait for a reply.")
r2("clusterprofiler","YuLab-SMU","clusterProfiler","devel","bug_report.md",
   "CONTRIBUTING.md: reproducible example with dput in a fresh session; markdown issue template (latest release, docs read, reproducible example; questions go to Bioconductor support/Biostars). The maintainer's 'how to bug author' guide and book were unreachable from the audit session: read them before posting. #819 read in full 2026-09-08 (thread-819.txt): the maintainer already named the CP5 cause and fix on 2026-06-22, so CP5 is dropped. CP1 is a heads-up only: fixed on devel, waiting for enrichit 0.2.2 to reach CRAN.",
   ["issue-cp1-gsea-table-rawp.md"], [], no_prs=True,
   order_note="Nothing to post here: CP5 dropped after reading #819 (already answered by the maintainer). CP1 is held: fixed and announced upstream. CP2/CP3/CP6/CP7 are fixed at master; CP8 is a design question.")
r2("enrichit","YuLab-SMU","enrichit","devel",None,
   "clusterProfiler's enrichment engine since 4.20 (CRAN package). No templates, NEWS + testthat. CP4 is a non-default option (gsea(method='sample'/'permute', adaptive=TRUE)) whose p-values are about half the GSEA convention; issue + git am-able patch with an exact-enumeration test. Fork exists; branch pushed.",
   ["issue-cp4-enrichit-sample-pvalue.md"], ["CP4"], dir="clusterprofiler", forked=True,
   order_note="Held: a rare option. File after a positive signal on the clusterProfiler thread.")
r2("gsea","GSEA-MSigDB","gsea-desktop","master",None,
   "CONTRIBUTING.md is the only contributing document: an issue with a title, description and executable test case; one-issue PRs referencing the issue. No .github directory (no issue or PR template), no AI policy, no DCO, no changelog, no linter; JUnit 5 tests exist but Gradle has no test task. A single maintainer (256 of 263 commits) and no merged external PRs seen, so PRs may sit. The GSEA website and binaries are behind domains the proxy blocks: master is v4.4.0 plus a readme commit, and old tags were built from source. No prior issue for any of the three findings (nearest #5, #14, #10, #50). Fork GSEA-MSigDB/gsea-desktop for the PRs.",
   ["issue-gs3-zero-weight-gene-set.md","issue-gs1-weighted-p15-negative-scores.md","issue-gs2-set-min-equals-max.md"], ["GS1","GS2","GS3"],
   forked=True, order_note="GS3 first: the default scoring scheme, silent, on a package 720 papers name (69 identify this program; the rest fgsea, clusterProfiler or unstated). GS1 follows once GS3 has an answer; GS2 after that (two-filing cap).")
r2("bcftools","samtools","bcftools","develop",None,
   "CONTRIBUTING.md is the samtools text verbatim, so the samtools rules apply again: a real-name DCO sign-off that an agent may not add, an `Assisted-by:` trailer on the commit and at the end of the PR body, and a human-written commit message and PR description. The kit's patch carries the trailer and no sign-off: after `git am`, rewrite the message in your own words and `git commit --amend -s`. No issue or PR template in bcftools; NEWS blocks per command; `make test` runs 2,480 tests (green before and after the patch; the new regression test fails 2 checks without it). No prior report (nearest #2003, #897, #1058, #2185). Fork samtools/bcftools for the PR.",
   ["issue-bc1-mpileup-mwu-biasz-int-overflow.md"], ["BC1"], forked=True,
   order_note="BC1 filed 2026-09-23 as #2594 with PR #2595 (commit 83b7888, signed off); fork CI green on all five workflows. Waiting for the maintainers; the six held notes stay held. The annotations were introduced in 1.13, so the cohort's two most-cited versions (1.9, 1.10.2) are unaffected; 1.13 onward is.")
r2("star","alexdobin","STAR","master",None,
   "CONTRIBUTING.md is the only contributing document: questions go to the rna-star Google group, the tracker is for bugs, and a report needs the exact command, observed vs expected, system information and Log.out attached. PRs must state that default behaviour does not change (this one can: only '.'-strand transcripts and genes change). No issue or PR template, no CI beyond `make STAR`, no test runner or linter; CHANGES.md bullet convention followed. No prior issue (nearest #1922, #1880, #2679, #735, #2253, #2020). Fork cindykrafft/STAR made 2026-09-24; branch pushed. Re-check the declines-AI topic before sending. Fork alexdobin/STAR for the PR.",
   ["issue-sta1-undefined-strand.md"], ["STA1"], forked=True,
   order_note="STA1 filed 2026-09-24 as #2707 + PR #2708. Nothing else here until the maintainer answers (the notes stay held).")
r2("trimmomatic","usadellab","Trimmomatic","main",None,
   "No contributing document, issue or PR template, linter, code of conduct or AI policy. versionHistory.txt is the changelog (last entry 0.40; the patches leave the line to the maintainers and the PR bodies offer it). CI runs `mvn -B clean verify` on JDK 25 for every push and PR. The tracker is active again (the 2021-2024 backlog was closed in 2025-2026; 0.41 released 2026-07). No prior report of either finding (nearest #52, #16, #74, #22, #84). Fork cindykrafft/Trimmomatic made 2026-09-24; both branches pushed (71fb53e, 2c78514 on main ef98d62), so the PR buttons are live; the fork's Maven CI runs on each push.",
   ["issue-tm1-palindrome-mismatch-penalty.md","issue-tm2-maxinfo-normalisation.md","comment-tmr1-91-v042.md"], ["TM1","TM2"], forked=True,
   order_note="TM1 filed 2026-09-24 as #90 + PR #91. sebeier (collaborator) replied 2026-09-25: confirmed on #90 (fix planned for 0.42) and asked on #91 to retarget to V0.42 and drop the dependency-reduced-pom.xml change. Done: (1) PR #91's base changed to V0.42; (2) the prepared branch force-pushed (54af058 on V0.42: fix + test only, 519 tests pass); (3) the TMR1 reply posted on #91 2026-09-25 13:35; waiting on sebeier. TM2 waits: MAXINFO was rewritten on V0.42 and the finding is being re-verified there first.")
r2("limma","bioc","limma","devel",None,
   "No tracker and no PRs: bioc/limma is a read-only mirror with issues disabled, and git.bioconductor.org is unreachable. The channel is the Bioconductor support site (tag limma) or the maintainer's e-mail, never a cold PR; the support site is unreachable from the audit session, so searching it for prior reports is step 1 and yours to do. The texts below are the two support-site posts; the three patches (LI1 for devel and RELEASE_3_23, LI2 for devel) are attached as diffs for the maintainers to apply, each with a test that fails on the unmodified code. No fork applies.",
   ["issue-li1-arrayweights-reml-convergence.md","issue-li2-voom-offset-double-count.md"], [], no_prs=True,
   order_note="LI1 first: worth sending before limma 4.0.0, whose new voomLmFit(sample.weights=TRUE) routes to the affected code by design. LI2 second, after LI1 has a reply.")
r2("featurecounts","ShiLab-Bioinformatics","subread","master",None,
   "The developers' GitHub mirror of Subread (release channel is SourceForge; user forum is the Subread Google Group; Rsubread goes to Bioconductor support). The GitHub tracker could not be read from the audit session (search returns nothing for the repo): check whether the maintainers answer issues there before sending anything. No CONTRIBUTING, templates, changelog or linter; tests are shell scripts with .ora expectations. FC2 changes numbers only for mixed single-end/paired-end libraries under stranded counting; FC1 is a rare option. Both patches add a test that fails on unmodified master.",
   ["issue-fc2-read-type-filter.md","issue-fc1-splitonly-singletons.md"], ["FC1","FC2"],
   order_note="Both held. If the maintainers do use the GitHub tracker, FC2 goes first as an issue (a 2.0.2 regression against the manual's own sentence), PR after their view.")
r2("fieldtrip","fieldtrip","fieldtrip","master",None,
   "PRs against master from a fork; no issue template. Five PRs and two issues are up already (the maintainer, schoffelen, is active on them: #2613 merged, #2610 carries his own commits). FT12 is the issue he asked for on #2610; FT13 and FT14 are replies on threads he wrote in, so they are exempt from the two-unanswered cap.",
   ["issue-ft17-external-stats-not-added.md","issue-ft12-dpss-hack-two-outputs.md","issue-ft13-reply-2610-tests.md","issue-ft14-reply-2609-edge-bins.md","issue-ft15-reply-2610-bandwidth.md","issue-ft16-reply-2614-scope.md"], [],
   order_note="FT17 filed 2026-09-23 as #2621 with PR #2622; the survey comment is on #2614. Everything FieldTrip is now waiting on the maintainers; the Octave FAQ page edit waits for their word on where it goes.")
r2("bedtools","arq5x","bedtools2","master",None,
   "HOLD (2026-09-08): PR #1143, PR #1144 and the #1142 comment are unanswered, which is the two-unanswered cap; BT1 waits for a maintainer signal. No CONTRIBUTING, templates, linter or changelog convention; CI is make test; docs/content/history.rst is a hand-edited per-release changelog. BT2 is a comment on open #1142; BT1 relates to open #673 (2018, same defect); BT6 relates to #1089. All five change published numbers, so open the issue and wait for a signal before the PR. BT3 and BT5 are issues only (their fixes need invasive changes).",
   ["issue-bt1-coverage-split-count.md","issue-bt2-intersect-split-F.md","issue-bt3-closest-tie-order.md","issue-bt4-large-chrom-coordinates.md","issue-bt5-pct-float-truncation.md"],
   ["BT1","BT2","BT4"])
r2("fastp","OpenGene","fastp","master",None,
   "HOLD (owner, 2026-09-05): fastp is up to date for now, PR #715 unanswered; FP1-FP3 wait. No CONTRIBUTING, templates, changelog or linter; CI builds and smoke-tests; ./fastp test and scripts/*.sh are the test conventions (PR 2 adds a script in that style). FP1 and FP3 are comments on open #474 and #518 (both 2023); #474 has one comment that could not be read from the audit session, read it before posting. FP2 is new.",
   ["issue-fp1-cut-window-trim-front.md","issue-fp2-known-adapter-over60.md","issue-fp3-indel-adapter-offset.md"], ["FP1","FP2","FP3"])
r2("plink","chrchang","plink-ng","master",None,
   "No CONTRIBUTING, templates, changelog or linter; PLINK 1.9 has no unit-test runner (1.9/tests needs a PLINK 1.07 build), so the PR carries its own exhaustive driver. No prior issue (nearest #128); several other audit-style issues (#341, #353, #363, #365) landed 2026-08-31 to 09-02, so read those first to avoid a duplicate. PLINK 2.0 is unaffected: the fix is to 1.9/plink_stats.c only.",
   ["issue-pl1-hwe-threshold-boundary.md"], ["PL1"])

r2("picard","broadinstitute","picard","master",None,
   "No CONTRIBUTING.md and no AI policy. The PR template carries a checklist that must stay in the PR body (tests added, docs if applicable, CI green on GitHub Actions, reviewer thumbs-up, rebase/squash); the bodies below include it. The issue template's header asks for a GATK support-forum post before a tracker issue; reproducible bugs with a fix go straight to the tracker in practice (#1971 and #1522 did), and the issue text works verbatim as a forum post if you prefer the letter of the rule. CI: TestNG on Java 17; each fix branch is one commit (fix + regression test that fails on master) and the project's own tests were run on it here. Nine prior threads read in full; none reports P1, P2 or P3 (#1278 is the GC-bias off-by-one, held with a comment drafted; #1971 is FOLD_80). Fork broadinstitute/picard so the three branches can be pushed.",
   ["issue-p1-rnaseq-coverage-last-base.md","issue-p2-hsmetrics-zero-cvg-targets-pct.md","issue-p3-alignment-summary-bisulfite-ref-index.md"], ["P1","P2","P3"], forked=True,
   order_note="P1 issue + PR first (CollectRnaSeqMetrics transcript coverage, default settings, every version), then P2 issue + PR (CollectHsMetrics zero-coverage fraction, regression since 2.19.0): the two-filing cap. P3 (bisulfite mismatch rate, a documented option) as soon as one of them has a reply. The three branches are on cindykrafft/picard (pushed 2026-09-26; Actions are not enabled on the fork, so CI runs on the upstream PR).")
r2("bowtie2","BenLangmead","bowtie2","master",None,
   "No CONTRIBUTING.md, no issue or PR template, no AI policy (README, MANUAL, .github searched; .github holds only the two test workflows). Bug reports with a reproduction go to the tracker. CI runs make simple-test (scripts/test/simple_tests.pl, Perl) on Linux, Linux without AVX2 and macOS for every PR; the script was run here on both fix branches. Each fix branch is one commit whose message carries the explanation. Twenty prior threads read in full through two helper sessions; none reports BW1, BW2 or BW4 (#430, open, is a different --no-mixed effect the maintainers said in 2023 they were fixing; #180/#346 are the soft-clip TLEN threads behind note N1). Fork BenLangmead/bowtie2 so the two branches can be pushed.",
   ["issue-bw1-mate2-mapq-opposite-length.md","issue-bw2-xs-missing-unpaired-mates.md","issue-bw3-no-mixed-suppresses-discordant.md","issue-bw4-maxins-boundary-spurious-insertions.md"], ["BW1","BW2"],
   order_note="BW1 issue + PR first: it is a master-only regression from 2026-09-14 (mate 2's MAPQ computed with its own length) that ships with the next release unless fixed; one-token change. Then BW2 issue + PR (XS:i never printed for unpaired-aligned mates; every version; six lines). That is the two-filing cap. BW3 (--no-mixed suppresses discordant alignments, manual says otherwise) and BW4 (spurious insertions just above -X, with the mechanism) go as reports once one of the first two has a reply. Fork first: the PR cards go live when the branches are on cindykrafft/bowtie2.")
r2("fastqc","s-andrews","FastQC","master",None,
   "No CONTRIBUTING file, no issue or PR template, no AI policy (README's Contributions section points to the tracker or the author's e-mail; .github holds dependabot and workflows). No test suite; the harness was run on the patched build. Twelve prior threads read in full through a helper session (see the kit README): #147 is the encoding misdetection that FQ1 follows up (the maintainer said in 2025 he had never seen a real dataset that needed an override and closed it in 2026-05 without a change; PR #210 by ewels, open, stops guessing for BAM/SAM only); none reports FQ2 or FQ3; PR #205 (ewels, open) already refines the mean/median length output, so note N2 stays held. Fork s-andrews/FastQC so the FQ2 branch can be pushed.",
   ["issue-fq1-encoding-detection-high-quality.md","issue-fq2-per-sequence-quality-mean-truncated.md","issue-fq3-gc-content-first-100-bases.md"], ["FQ2"],
   order_note="FQ1 first as a report that follows up the closed #147 with a proposed default (every quality reported 31 too low when no base is below Q31; the one finding that turns a whole report red), then FQ2 issue + PR (per-read mean quality truncated; one-line fix). That is the two-filing cap. FQ3 (GC module uses the first 100 bases of 150-bp reads; page says whole read) once one of them has a reply. Fork first: the PR card goes live when the branch is on cindykrafft/FastQC.")
r2("vcftools","vcftools","vcftools","master",None,
   "No CONTRIBUTING file, no .github directory, no issue or PR template, no AI policy; the README says the Issues page is the way to get help. No test suite or CI. Twelve prior threads read in full through a helper session (see the kit README): none reports VT1 or VT2; #28 (2016, closed by its reporter) is VT3, the reporter worked out that --max-missing-count counts alleles and nobody replied; #189 is the --012 biallelic-only question (held comment in the kit). No maintainer reply in any thread read (2016-2024) and four open PRs since 2016: expect a slow or no response. Fork vcftools/vcftools so both branches can be pushed.",
   ["issue-vt1-tmpname-buffer-overflow.md","issue-vt2-relatedness2-missing-genotypes.md","issue-vt3-max-missing-count-alleles-vs-genotypes.md"], ["VT1","VT2"],
   order_note="VT1 issue + PR first (every temporary-file output mode, --012 / --plink / --hap-r2 / --geno-r2 and nine more, aborts with 'buffer overflow detected' on a source build with a current compiler; 19-line fix), then VT2 issue + PR (--relatedness2 kinship scaled down by the pairwise call rate when genotypes are missing: duplicates 0.40 instead of 0.50 at 20 % missing; fix verified). That is the two-filing cap (issue + PR pairs count as one). VT3 (--max-missing-count counts alleles, manual says genotypes; #28 found it in 2016) once one of them has a reply. Fork first: both PR cards go live when the branches are on cindykrafft/vcftools.")
r2("scdblfinder","plger","scDblFinder","devel",".github/ISSUE_TEMPLATE/bug_report.md",
   "Bug-report template (Describe the bug / MRE / Traceback / Session info; 'ensure that it is reproducible with a recent Bioconductor and scDblFinder version'); no CONTRIBUTING, PR template or AI policy. Twelve prior threads read in full through a helper session (see the kit README): none reports SD1, SD2 or SD3; #52 is a user wanting exactly the per-combination stats that SD1/SD2 break. The maintainer answers within a day and acknowledges bugs plainly (#57). The numbers were produced on 1.16.0 (this session's R cannot install devel); the touched code is identical on devel and every MRE runs on any version. Fork plger/scDblFinder so the three branches can be pushed.",
   ["issue-sd1-artificial-doublet-origins.md","issue-sd2-factor-cluster-labels.md","issue-sd3-dbr-threshold-nan.md"], ["SD1","SD2"],
   order_note="SD1 issue + PR first (artificial doublets get another pair's origin label with the default adjustSize, so scDblFinder.mostLikelyOrigin is right 24 % of the time; calls unaffected; contained fix), then SD2 issue + PR (a factor clusters argument empties scDblFinder.stats and returns integer codes in scDblFinder.cluster). That is the two-filing cap. SD3 (doubletThresholding(method='dbr') returns NaN without artificial doublets) once one of them has a reply. Fork first: the PR cards go live when the branches are on cindykrafft/scDblFinder.")
r2("scikit-learn","scikit-learn","scikit-learn","main",".github/ISSUE_TEMPLATE/bug_report.yml",
   "AUTOMATED CONTRIBUTIONS POLICY (doc/developers/contributing.rst): no issues or PRs from fully automated tools; 'do not paste AI generated text in the description of issues, PRs or in comments'; AI use must be stated in the PR description (the PR template's disclosure list); bug reports get 'Needs Triage' and a PR must not be opened until the label is removed. The texts here are fact sheets (reproducer, output, numbers, analysis): write the issue in your own words from them, paste the reproducer and its output verbatim, and put your own sklearn.show_versions() block in Versions. Seven prior threads read in full through two helper sessions (see the kit README), including the 48 review threads of the solver's PR #27491: none reports SK1 or SK2; #29534 is a different covariance_eigh instability (rank-deficient data with whiten=True) that the SK1 text links. Fork scikit-learn/scikit-learn so both branches can be pushed.",
   ["issue-sk1-pca-covariance-eigh-offset.md","issue-sk2-nmf-reconstruction-err.md"], ["SK1","SK2"],
   order_note="SK1 issue first, written in your own words (PCA's covariance_eigh solver, the auto choice for tall dense data since 1.5, loses the variance of offset features: 33 % off for float32 values around 100, meaningless around 1e3; the full solver is exact). Its PR card is for AFTER the issue is triaged (label 'Needs Triage' removed, direction agreed): the repository rule. SK2 (NMF.reconstruction_err_ docstring) can go straight in as the doc PR, or as the documentation issue first. That is the two-filing cap. In every PR body keep the 'AI usage disclosure' list as it applies and write the rest yourself. Fork first: the PR cards go live when the branches are on cindykrafft/scikit-learn.")
r2("numpy","numpy","numpy","main",".github/ISSUE_TEMPLATE/bug-report.yml",
   "AI POLICY (doc/source/dev/ai_policy.rst): 'do not use AI to automatically generate comments, pull request descriptions, or issue descriptions'; 'do not use AI to speak for you' in issues and PRs; AI use must be disclosed in the PR (tools, how, what is generated) or it is rejected; an AI agent may not submit a PR autonomously; non-maintainers may have at most 2 non-draft PRs open. The texts here are FACT SHEETS: write the issue and PR prose in your own words, paste the reproducer and its output as they are, fill 'How does this issue affect you or how did you find it' yourself. Prior-report search over ten topics; nineteen threads read in full through a helper session (see the full-inspection ledger): no report of NP3 or NP5. Fork numpy/numpy for the NP3 branch.",
   ["issue-np3-unique-nat-equal-nan.md","issue-np5-select-wraps-python-int.md"], ["NP3"],
   order_note="NP3 issue first, in your own words (since the 2.3/2.4 hash path, np.unique(datetime, equal_nan=False) merges NaT unless an optional output is requested; the complex NaN representative is not the documented smallest one), then its PR from the verified branch, with the AI disclosure. NP5 issue second (np.select wraps an out-of-range Python int into the result dtype, 300 -> 44 in int8; np.where had the same bug and raises since 2.5). That is the two-filing cap. Keep the reproducers as short as they are: on the one AI-assisted report of this batch (#32522) a maintainer's first reply was about readability.")
r2("alphafold3","google-deepmind","alphafold3","main",None,
   "CONTRIBUTING.md: small bug-fix and documentation patches only; AI-generated code, docs or PR text is welcome if it is declared in the PR message, manually reviewed and manually tested (they may ask you to fold an input; hallucinated test results are called out). Google CLA required before any PR (https://cla.developers.google.com/): PR #734 got the CLA-bot failure and the maintainer applied the fix himself, with credit. No issue or PR templates. Fork exists; branches fix/to-json-preserves-chain-order (fix + regression test) and fix/summary-confidences-chain-ids pushed, both merge cleanly into main a66cc52. Prior-report search 2026-09-22: no match for either; #150, #476 and PR #678 read in full 2026-09-22: in #678 the maintainer agreed the chain_ids field should be 'the deduplicated unique chain ID list ... in the same order as the positional arrays' and his commit dropped the de-duplication the PR had, so AF2 is a regression against the agreed design; #150/#476 promise users that the chain order follows the sequences field, which AF1 breaks for the two-stage run. The PR bodies carry the AI declaration and say you reviewed and ran the tests: do both before opening (audits/alphafold3/upstream/pr-bodies.md has the commands).",
   ["issue-af1-to-json-chain-order.md","issue-af2-summary-confidences-chain-ids.md"], ["AF1","AF2"], forked=True,
   order_note="Sign the CLA first. Then AF1 issue + PR (to_json reorders interleaved identical chains, so the two-stage _data.json workflow runs a different complex; regression test on the branch), then AF2 issue + PR (summary_confidences chain_ids is per token, 150 entries against 2 chains on the shipped test output). That is the two-filing cap; the other twelve branches (audits/alphafold3/upstream/README.md) wait for a reply, and the two model-behaviour findings (cross-attention key mask, MSA pairing sort order) go as issues without PRs when their turn comes.")

# ---- triage (2026-09-03): file only findings that change published numbers under default/common settings; at most two per repo until a maintainer responds
TIER={"filed":{"TMR1":"reply on PR #91 posted 2026-09-25 13:35 (base V0.42, branch 54af058; waiting on sebeier)","BC1":"#2594 / PR #2595 (2026-09-23; fork CI green)","AF2":"#746 / PR #747 (2026-09-23)","FT17":"#2621 / PR #2622 (2026-09-23)","FT12W":"fieldtrip/website PR #958 (dpss FAQ page), merged 2026-09-23","AF1":"#744 / PR #745 (2026-09-22)","DT1":"comment on #1108 (closed 2026-09-05)","CA1":"#892 / PR #893","U1":"#1286 / PR #1287 (merged 2026-09-05)","CPDB1":"#231","DTN1":"#1457 / PR #1458","DTN2":"#1459 / PR #1460 (closed 2026-09-18: WardDeb confirmed the bug and fixed it differently in #1472, merged the same day)","BT2":"comment on #1142 / PR #1144 (2026-09-05)","FT12":"#2614 (2026-09-05; schoffelen 2026-09-16: FAQ wanted as a fieldtrip/website PR, Octave survey welcome; the FAQ PR fieldtrip/website#958 was merged 2026-09-23)","FT13":"posted on PR #2610 (2026-09-05)","FT14":"posted on #2609 (2026-09-05)","FT15":"posted on PR #2610 (2026-09-07, per the comment count)","FT16":"posted on #2614 (2026-09-07, per the comment count)","PL1":"#380 / PR #381 (closed 2026-09-03: the maintainer applied his own equivalent fix, 1fe42e5)","DT4":"comment on #1118 / PR #1466 (2026-09-08)","ST1":"#2378 / PR #2379 (2026-09-08; merged 2026-09-24)","STA1":"#2707 / PR #2708 (2026-09-24)","TM1":"#90 / PR #91 (2026-09-24; sebeier 2026-09-25: confirmed, planned for 0.42, retarget to V0.42 and drop the POM change)","ST3":"comment on #696 / PR #2388 (2026-09-24; fork CI green on 47d3376)","LM2":"comment on #867 / PR #1000 (2026-09-08)","GS3":"#74 / PR #75 (2026-09-14)"},
      "now":["P1","P2","BW1","BW2","FQ1","FQ2","VT1","VT2","SD1","SD2","SK1","SK2","NP3","NP5","HC2","EG3","GS3","LI1"],
      "comment":[]}
def tier_of(i):
    if i in TIER["filed"]: return "filed"
    if i in TIER["now"]: return "now"
    if i in TIER["comment"]: return "comment"
    return "held"
for r in repos.values():
    for i in r["issues"]:
        i["tier"]=tier_of(i["id"]); 
        if i["tier"]=="filed": i["filed_as"]=TIER["filed"][i["id"]]
    for p in r["prs"]:
        p["tier"]=tier_of(p["needs"])
        if p["tier"]=="filed": p["filed_as"]=TIER["filed"][p["needs"]]
    for d in r.get("discussions",[]): d["tier"]="held"
repos["star"]["issues"][0].update(tier="filed", filed_as="#2707 (2026-09-24)")   # STA1: issue filed, PR waits for the fork
for k in ("htseq","deeptools","bedtools","fastp","plink","fieldtrip"): repos[k]["forked"]=True
# repositories whose maintainers decline AI-generated contributions (topic on the fork; mirrored in site/audits.json)
import json as _j
_cfg=_j.load(open(ROOT+"/site/audits.json"))
_declined={a["dir"] for a in _cfg["audits"] if a.get("declines_ai")}
for k,r in repos.items():
    r["declines_ai"]= k in _declined or (k=="scanpy" and "scanpy" in _declined)

# ---- issue fixes (README step 6): audits/<pkg>/issue-fixes/<n>-<slug>/
import glob, os
UP={"spm":("spm","spm","main"),"fieldtrip":("fieldtrip","fieldtrip","master"),"afni":("afni","afni","master"),"freesurfer":("freesurfer","freesurfer","dev"),
    "kilosort":("MouseLand","Kilosort","main"),"suite2p":("MouseLand","suite2p","main"),"scanpy":("scverse","scanpy","main"),"umap":("lmcinnes","umap","master"),
    "cutadapt":("marcelm","cutadapt","main"),"cellphonedb":("ventolab","CellphoneDB","master"),"plink":("chrchang","plink-ng","master"),"deeptools":("deeptools","deepTools","master"),
    "bedtools":("arq5x","bedtools2","master"),"fastp":("OpenGene","fastp","master"),"iqtree":("iqtree","iqtree3","master"),"macs2":("macs3-project","MACS","main")}
FORK={"spm":"cindykrafft/spm","fieldtrip":"cindykrafft/fieldtrip","afni":"cindykrafft/afni","freesurfer":"cindykrafft/freesurfer","kilosort":"cindykrafft/Kilosort","suite2p":"cindykrafft/suite2p",
      "scanpy":"cindykrafft/scanpy","umap":"cindykrafft/umap","cutadapt":"cindykrafft/cutadapt","cellphonedb":"cindykrafft/CellphoneDB","plink":"cindykrafft/plink-ng","deeptools":"cindykrafft/deepTools",
      "bedtools":"cindykrafft/bedtools2","fastp":"cindykrafft/fastp","iqtree":"cindykrafft/iqtree3","macs2":"cindykrafft/MACS"}
PUSHED=set(open(ROOT+"/site/pushed-branches.txt").read().split()) if os.path.exists(ROOT+"/site/pushed-branches.txt") else set()
# replies drafted for a thread and not yet posted by the owner
PENDING_REPLY=set()   # the #214 reply was posted 2026-09-10
FILED={}
for line in open(ROOT+"/site/filed-fixes.txt"):
    line=line.strip()
    if not line or line.startswith("#"): continue
    pkg,issue,what,num,state=line.split(":"); FILED[(pkg,int(issue))]=dict(what=what,num=int(num),state=state)
fixes=[]
for d in sorted(glob.glob(A+"*/issue-fixes/*/")):
    pkg=d.split("/audits/")[1].split("/")[0]; slug=os.path.basename(d.rstrip("/")); n=int(slug.split("-")[0])
    if not (os.path.exists(d+"pr-body.md") and os.path.exists(d+"README.md") and glob.glob(d+"0001-*.patch")): continue
    pb=read(d+"pr-body.md"); m=re.search(r"^Title:\s*(.+)$", pb, re.M); title=m.group(1).strip(); body=foot(pb[m.end():].strip())
    cm=read(d+"comment.md") if os.path.exists(d+"comment.md") else ""
    # the kit's internal "Title: ..." first line is never part of what gets pasted
    cm=re.sub(r"\A\s*Title:[^\n]*\n+", "", cm)
    patches=sorted(glob.glob(d+"0001-*.patch")); branch=None
    rm=re.search(r"`(fix/issue-\d+[^`]*)`", read(d+"README.md")) if os.path.exists(d+"README.md") else None
    branch=rm.group(1) if rm else f"fix/issue-{n}"
    o,r,base=UP[pkg]; fork=FORK[pkg]
    pushed=[p.split(":",1)[1] for p in PUSHED if p.split(":",1)[0]==fork.split("/")[1] and p.split(":",1)[1].startswith(f"fix/issue-{n}")]
    if pushed: branch=pushed[0]
    assigned=read(d+"assigned.txt").strip() if os.path.exists(d+"assigned.txt") else ""
    fixes.append(dict(comment_pending=((pkg,n) in PENDING_REPLY), filed=FILED.get((pkg,n)), stale=(pkg in STALE_OFF), pkg=pkg, owner=o, repo=r, base=base, fork=fork, assigned=assigned, forked=(fork.split("/")[1]+":"+branch) in PUSHED, issue=n, title=title, body=body, comment=foot(cm.strip()) if cm.strip() else "", branch=branch,
                      declines=(pkg in _declined)))
json.dump(fixes, open(os.path.join(OUT,"fixes.json"),"w"), indent=1)
# ---- ordered action list (2026-09-08): what to do next, top first; everything else waits for a signal
def note(path):
    """A reply draft from a kit file: drop the internal Title line and the <!-- --> notes, keep the text to paste."""
    t=read(ROOT+"/"+path)
    t=re.sub(r"<!--.*?-->", "", t, flags=re.S)
    t=re.sub(r"\A\s*Title:[^\n]*\n+", "", t)
    return t.strip()+"\n"
ACTIONS=[
 dict(kind="issue", key="picard", id="P1", why="ISSUE FILED as #2060 (2026-09-26 00:02); next step: open the PR from cindykrafft:fix/rnaseq-coverage-last-base against master (the PR card below already says Fixes #2060). CollectRnaSeqMetrics never counts the last base of an alignment block in transcript coverage, so every internal exon end sits at ~0: a uniformly covered transcript reports CV 0.032 and a 0.91 dip at the junction; a realistic library shifts MEDIAN_CV_COVERAGE 0.430 to 0.436 and the 3' end of the gene-body curve by -9 %; 2.18.7 through master; one-line fix with a regression test on the branch (branch on cindykrafft/picard)"),
 dict(kind="issue", key="picard", id="P2", why="CollectHsMetrics ZERO_CVG_TARGETS_PCT divides the unique uncovered targets by the raw interval count: 0.5 for a true 0.667 with overlapping target intervals; a regression since Picard 2.19.0 (htsjdk 2.19.0 stopped merging IntervalList.fromFiles); one-line fix with a test on the branch"),
 dict(kind="issue", key="bowtie2", id="BW1", why="master-only regression (41ee86b, 2026-09-14, unreleased): reportHits computes mate 2's MAPQ with mate 2's own length as the opposite mate's, so mates of unequal length get different MAPQs for the same concordant pair (40/23 for a 150/50-bp pair with 3+2 mismatches; 6/30 for a perfect 150/60-bp pair in a repeat); releases 2.3.5.1-2.5.4 give both mates the same value; one-token fix on the branch (PR card goes live once BenLangmead/bowtie2 is forked)"),
 dict(kind="issue", key="bowtie2", id="BW2", why="every version: a mate reported as an unpaired alignment (YT:Z:UP) never carries XS:i even when it has a second-best alignment, MAPQ 0/1 and the summary counts it under 'aligned >1 times' (30/30 in the harness); the 'no XS = uniquely mapped' recipe keeps those multi-mappers; six-line fix on the branch"),
 dict(kind="issue", key="fastqc", id="FQ1", why="every version: a Phred+33 file whose lowest quality is 31 or more ('@') is read as Illumina 1.5, so every quality is reported 31 too low (Q37 -> 6) and the quality modules go red; two-colour instruments with a Q30 filter produce such files; follows up the closed #147 (maintainer: never seen a real dataset that needed it) with a reproduction, the filtered-file argument and a proposed default (offset 33 unless a character above 'J' is present) or an --encoding option"),
 dict(kind="issue", key="fastqc", id="FQ2", why="every version: each read's mean quality is truncated toward zero before binning (integer division), so the per-sequence quality histogram and the value its warn/fail thresholds test sit 0.5 too low on average (29.53 for a true 30.02 on 2,000 reads); one-line fix on the branch (PR card goes live once s-andrews/FastQC is forked)"),
 dict(kind="issue", key="vcftools", id="VT1", why="every version: the thirteen output modes that go through a temporary file (--012, --plink, --hap-r2, --geno-r2, --geno-chisq, the interchromosomal and SNP-list r2 modes, --ldhat, --ldhelmet) copy the mkstemp template into a stack buffer one byte too small; built from source on Ubuntu 24.04 / Fedora / Debian 13 (fortified strcpy by default) each aborts with 'buffer overflow detected' before writing anything; 19-line fix on the branch, every mode verified on the patched build (PR card goes live once vcftools/vcftools is forked)"),
 dict(kind="issue", key="vcftools", id="VT2", why="every version: --relatedness2 counts each individual's heterozygous sites over all its called sites while the numerator uses only sites called in both, so with missing genotypes the KING-robust kinship is scaled down by the pairwise call rate: duplicates 0.40 instead of 0.50 and parent-offspring 0.19 instead of 0.24 at 20 % missing, across the cut-offs users apply; fix on the branch gives the KING values (PR card goes live once the fork exists)"),
 dict(kind="issue", key="scdblfinder", id="SD1", why="every release since 1.4.0: with clusters given, createDoublets returns the size-adjusted 25 % of the artificial doublets after the others while getArtificialDoublets attaches the origin labels in the input order, so about half the artificial doublets are labelled with another pair of clusters and scDblFinder.mostLikelyOrigin is right for 24 % of heterotypic doublets on a simulated capture (100 % with the order kept); doublet calls unchanged; also a wrong halving count and a crash when one pair is adjusted; fix on the branch, testthat 17/17 (PR card goes live once plger/scDblFinder is forked)"),
 dict(kind="issue", key="scdblfinder", id="SD2", why="1.8.0 to devel: clusters passed as a factor (a colData column, mockDoubletSCE()$cluster) are stored as integer codes in the results table while the origins use the level names, so metadata(sce)$scDblFinder.stats shows 0 observed doublets for every combination with NA FNR and difficulty, plotDoubletMap is empty, and scDblFinder.cluster holds 1, 2, 3 instead of the labels; character labels work; one-line fix on the branch (PR card goes live once the fork exists)"),
 dict(kind="issue", key="scikit-learn", id="SK1", why="every release since 1.5.0: PCA's covariance_eigh solver, which svd_solver='auto' selects for dense data with at most 1000 features and at least ten times as many samples, forms the covariance as X.T @ X - n * mean (x) mean and loses the variance of features with a common offset to cancellation: float32 values around 100 with unit spread give explained_variance_ 33 % off, around 1e3 87 % off (ratio 54 %); float64 values around 1e6 1.7 % off, 1e7 20 % (PC1 scores 3.5 %), 1e8 meaningless; the full solver (the auto choice up to 1.4) is exact throughout; batched centred accumulation with the same memory footprint verified (harness 62/62, new test fails on main, test_pca.py 388 passed on the patched install); no prior report. WRITE THE ISSUE IN YOUR OWN WORDS from the fact sheet (repository policy); the PR follows triage"),
 dict(kind="issue", key="scikit-learn", id="SK2", why="every version: NMF.reconstruction_err_ and MiniBatchNMF.reconstruction_err_ are documented as 'Frobenius norm ... or beta-divergence' but are sqrt(2 * D_beta) for every loss: 40.12 for a KL divergence of 804.56; docstring patch on the branch. The documentation template allows a direct PR instead of an issue; either way, your own words (repository policy)"),
 dict(kind="issue", key="numpy", id="NP3", why="2.3+ (hash path of np.unique): np.unique(a, equal_nan=False) on datetime64 merges the NaT values when no optional output is requested, while return_counts/index/inverse, float NaN and every 1.x keep them; the complex NaN representative is the first met, not the documented smallest (np.unique(c) and np.unique(c, return_counts=True)[0] differ); fix verified on a source build of main (4 new test cases fail before, 643 passed after); no prior report. WRITE THE ISSUE AND PR TEXT IN YOUR OWN WORDS (NumPy AI policy); disclose AI use in the PR"),
 dict(kind="issue", key="numpy", id="NP5", why="every 2.x release and main: np.select with an int8 choice and default=300 returns 44 silently (-129 -> 127; a Python int among the choices wraps too); 1.x promoted to int16; np.where had the same bug and raises OverflowError since 2.5 (gh-30803); no prior report. Your own words (NumPy AI policy)"),
 dict(kind="issue", key="limma", id="LI1", why="a Bioconductor support-site post, not a GitHub issue: arrayWeights(method='reml') with prior weights divides its convergence criterion by the gene count twice, so it stops after two iterations instead of five and the weights differ by up to 14.7 percent from the same model without weights (137 vs 183 DE genes with voomWithQualityWeights); devel's voomLmFit(sample.weights=TRUE) routes there by design, so send it before limma 4.0.0; search the support site for prior reports first"),
 dict(kind="issue", key="edger", id="EG3", why="support-site post, not a GitHub issue: filterByExpr drops a gene sitting exactly on the CPM cutoff by one ulp, every version, one-line fix attached; small effect, so post only if you are comfortable with a low-magnitude report"),
]
WAITING=[
 ("NumPy full-inspection queue: NP2 (RandomState.set_state with an out-of-range pos segfaults on the next draw; a public bug under NumPy's security policy), NP10 (StringDType strip skips an ASCII character after a multi-byte one in chars), NP9 (zipf near a = 1), NP11 (Polynomial.integ lbnd)", "a reply on NP3 or NP5 (the two-filing cap); facts in audits/numpy/full-inspection.md"),
 ("scikit-learn full-inspection queue: SK6 (f_regression p = 1 for a feature equal to the target; #34834 does not cover it), SK5 (cosine KDE mis-normalised in even dimensions), SK7 (TSNE squares a precomputed D in place), then the branches SK12, SK10, SK11, SK9 and SK8 (as an offer on #24732); SK4 possibly as a comment on #25380 / PR #27763 once #27763's reviews are read", "a reply on SK1 or SK2 (the two-filing cap); facts in audits/scikit-learn/full-inspection.md"),
 ("FastQC FQ3 (Per sequence GC content uses only the first 100 bases of 101-199-bp reads while the page says the whole read; report, page or code)", "a reply on FQ1 or FQ2 (the two-filing cap); the text is in the kit"),
 ("VCFtools VT3 (--max-missing-count excludes sites by missing alleles while the manual says missing genotypes, twice as strict for diploids; #28 found it in 2016 and nobody replied; documentation issue with a man-page patch)", "a reply on VT1 or VT2 (the two-filing cap); the text is in the kit"),
 ("scDblFinder SD3 (doubletThresholding(method='dbr') returns NaN on the documented minimal input, a table with only a score column; fix on the branch)", "a reply on SD1 or SD2 (the two-filing cap); the text is in the kit"),
 ("scikit-learn SK1 PR (fix/pca-covariance-eigh-centering: batched centred covariance for the covariance_eigh solver, regression test, changelog fragment to rename to <PR>.fix.rst)", "the SK1 issue to be triaged ('Needs Triage' label removed, direction agreed): the repository rule before any code PR"),
 ("Bowtie 2 BW3 (--no-mixed also suppresses discordant alignments; report, code or manual) and BW4 (spurious 2-12-bp insertions on one mate of pairs 18-33 bp longer than -X, 0.4 % of mates on a realistic library; report with the mechanism, PR after the maintainers pick the shape)", "a reply on BW1 or BW2 (the two-filing cap); both texts are in the kit"),
 ("Picard P3 (bisulfite mismatch rate, one-token fix with a test), P4 (GC-bias window off-by-one, a comment drafted for #1278), P5-P7", "a reply on P1 or P2 (the two-filing cap); P3 is ready to go the moment one arrives"),
 "samtools: ST1 (#2378 / PR #2379) merged 2026-09-24 by daviesrob; ST3 filed 2026-09-24 as the comment on #696 + PR #2388; the branch's executable-bit slip is fixed and the fork's five workflows are green on 47d3376; N1, N4, N5, N6 stay held",
 "BCFtools: #2594 + PR #2595 (BC1, mpileup bias Z-scores) filed 2026-09-23; the fork's five CI workflows are green on the signed-off commit; nothing else to file there",
 "AlphaFold 3: #744 + PR #745 (to_json chain order, 2026-09-22) and #746 + PR #747 (chain_ids per token, 2026-09-23): the two allowed; CLA check on both PRs to watch; the other twelve branches wait for a reply",
 "FieldTrip: #2621 + PR #2622 (external/stats regression + Octave shims, 2026-09-23, fourth commit 99b4c3c and the reply to the test bot posted 2026-09-23 19:39) and the Octave survey comment on #2614 (2026-09-23) posted; waiting on schoffelen or Robert; the Octave FAQ page edit (website-faq-octave-edit.md) goes as a website PR if schoffelen or Robert says so",
 "AFNI: #967 answered 2026-09-22 (the saturation-value reply), PR #960 closed with the closing note and #959 closed the same evening; waiting on afni-dglen for #967",
 ("GSEA GS1 (weighted_p1.5 raises the signed score to a fractional power: NaN hit weights, sign flips) and GS2 (set_min == set_max skips the size filter and can abort the run)", "an answer on GS3; GS1 next, then GS2 (two-filing cap)"),
 ("Trimmomatic TM2 (MAXINFO trims every read to one base for targetLength >= 248 at strictness 0.1, >= 711 at any strictness: long-range saturation) and notes N1-N8", "TM1 has its answer (2026-09-25); MAXINFO was rewritten on V0.42, so TM2 is being re-verified on V0.42 before the text and branch are rebuilt against it"),
 ("limma LI2 (voom() double-counts an edgeR-style offset: a no-op offset shifts E by up to 1.5 log2 units per column, 5374 vs 37 genes called; devel's voomLmFit reads the same slot the other way) and notes N1-N9", "a reply on the LI1 support-site post"),
 ("STAR N1-N5 (spliced-vs-clipped ties reported as two loci; 2-pass junctions counted as annotated in Log.final.out; a non-canonical junction displaced to a canonical motif)", "a maintainer signal on STA1 (#2707 / PR #2708, filed 2026-09-24)"),
 ("BCFtools N1-N6 (merge takes an A/R/G tag from the last file, not the first as documented; -d is a memory guard, not a per-position cap; multiallelic HWE double-counts REF)", "a maintainer signal on BC1"),
 ("lme4 LM1 (master-only Gamma logLik dispersion mismatch), LM3", "a reply on the #867 comment or PR #1000 (both filed 2026-09-08, the two-unanswered cap); LM1 is a pre-release heads-up worth sending before 2.x ships"),
 ("enrichit CP4 (sample-permutation p-values halved, rare option)", "the owner's call: #819 shows the maintainer fixing enrichit reports within weeks, so CP4 could go straight to YuLab-SMU/enrichit as issue + PR (branch on the fork) without waiting for a signal on a clusterProfiler thread"),
 ("featureCounts FC2 (read-type filter lost in 2.0.2), FC1", "confirmation that the maintainers answer GitHub issues on ShiLab-Bioinformatics/subread"),
 ("clusterProfiler CP1 (release GSEA table filtered on raw p)", "never as a report: fixed on devel; a heads-up only if enrichit 0.2.2 is slow to reach CRAN"),
 ("BEDTools BT1 (coverage -split counts blocks)", "a reply on #1142, PR #1143 or PR #1144 (cap reached)"),
 ("CellPhoneDB CPDB2 (p-value ties, p = 0)", "a reply on #231 or PR #232 (cap reached)"),
 ("fastp FP2 (adapter over 60 bases), FP1, FP3", "owner's hold of 2026-09-05; PR #715 unanswered"),
 ("Scanpy #3809 fix, SR1/SR3 (Scrublet port)", "a reply on PR #4337 or #4336"),
 ("Kilosort #1039 fix", "PR #1043 was merged 2026-09-25 23:54 (the KS4 refractoriness gate fix); PR #1045 and issues #1044/#1046/#1047 are still unanswered, over the two-filing cap, so the #1039 fix waits for one of them"),
 ("Suite2p #1079 (assigned upstream; comment only)", "a reply on PR #1266-#1268 or issues #1265/#1269/#1270"),
 ("FieldTrip #2345 fix", "#2608, #2610, #2611 or #2612 merged or answered; #2610 is 'almost ready to merge' and our 2026-09-07 answer on the normalisation is the last comment; #2608, #2611, #2612 have no maintainer comment"),
 ("deepTools DT1, DT5, DT8, DT9, DTN3", "a reply on #1457/#1458 (bamCompare --operation) or PR #1466 (MNase); DTN2 is settled: WardDeb confirmed the plotPCA bug on 2026-09-18 ('the bug is correct') and fixed it his own way in #1472 (merged 2026-09-18: samples-as-observations is now the only layout, --transpose and --rowCenter removed)"),
 ("IQ-TREE PR #214 (SH-aLRT with -j/-J)", "bqminh's re-review: his changes-requested review of 2026-09-10 asked for the CI additions to be removed, which was done and answered the same day (comment of 2026-09-10 14:56); CI green on 04f81848; nothing since"),
 ("SPM and AFNI second fixes", "not chosen yet; SPM's first fixes and AFNI's #944/#947/#926/#928, #958 and #962 (merged 2026-09-18) and the R-script fixes of #960 (applied on master by Gang Chen 2026-09-22 with credit; the PR sits open with an empty diff) are in, so they are next to prepare; five AFNI PRs still carry unmerged code"),
 ("umap third fix, IQ-TREE third fix", "PR #1288 / PR #210 answered"),
 ("HTSeq HC1/HC2, FreeSurfer #1358", "never: the maintainers decline AI-generated contributions"),
]
json.dump(dict(actions=ACTIONS, waiting=WAITING), open(os.path.join(OUT,"actions.json"),"w"), indent=1)
print("issue fixes:", [(f["pkg"], f["issue"], f["forked"]) for f in fixes])
for k,msg in {}.items():
    if k in repos:
        repos[k]["order_note"]=msg; repos[k]["stale"]=True
        for p in repos[k]["prs"]:
            if p["tier"]!="filed": p["tier"]="held"
json.dump(repos, open(os.path.join(OUT,"data.json"),"w"), indent=1)
enc=lambda s: u.quote(s, safe="-_.!~*'()")
for k,r in repos.items():
    for i in r["issues"]:
        if "description" in i: n=len(enc(i["title"]))+len(enc(i["description"]))+len(enc(i["code"]))+len(enc(i["traceback"]))+len(enc(i["versions"]))
        else: n=len(enc(i["title"]))+len(enc(i["body"]))
        print(f"{k:12} {i['id']:6} prefill length ~{n+80}")
    for p in r["prs"]: print(f"{k:12} PR {p['id']:5} ~{len(enc(p['title']))+len(enc(p['body']))+80}")
